/* 3챕터 장비 효과 점검 (10월 8일, docs/아이템/3챕터-장비.md 8절): 06a2의 게임 코드를 vm에서 그대로 돌려, 장비의 새 지점과 핵심 효과가 문장대로 일어나는지 장면마다 확인한다.
   itemcheck는 "발동했는가"를 세고, 이 점검은 "문장대로 바뀌었는가"를 본다. 실패 0이어야 한다.
   실행: DGDIR=06a2 node tools/item3check.js */
process.env.DGDIR = process.env.DGDIR || '06a2';
const D = require('./dgqa.js'); const G0 = D.G0; const run_ = D.run_;
let fail = 0, pass = 0; const ok = (c, m) => { if (c) pass++; else { fail++; console.log('실패:', m); } };
const V = k => run_(k);
function battle(room, build, lv, items) {
  const bd = build || 'warden';
  const p = G0.mkPlayer(bd, {}, G0.statRecommend(bd, {}, 15 + 2 * ((lv || 13) - 1)), G0.TREE2[bd].starters); p.lv = lv || 13;
  for (const k of items || []) p.eq[G0.ITEMS[k].slot] = k;
  p.stat.wil = 0; G0.applyStats(p, p.stat || {}); p.hp = p.hpMax; p.st = p.stMax;
  const r = Object.assign({ ch: 3, lv: 11, floor: 14, names: V('ENEMY_NAMES[3]'), path: 'main', en: [] }, room);
  const b = G0.roomBattle(p, r, r.boss ? 'queen' : null, 7); b.stepMode = false; for (const e of b.en) { e.hpMax = 100000; e.hp = 100000; } return b; /* 한 번에 쓰러지지 않게 생명력을 부풀린다 */
}
const al = b => G0.alive(b);
/* 한 번 친다: 행동 번호를 올리고 b.cur를 두고 hurtEnemy를 부른다 */
function hit(b, e, raw, cur, o) { b.actN = (b.actN || 0) + 1; b.cur = cur || { id: 'basic' }; const h0 = e.hp; G0.hurtEnemy(b, e, raw, o || { single: 1, melee: 1 }); b.cur = null; return h0 - e.hp; }
function T(name, f) { try { f(); } catch (x) { ok(false, name + ' 예외: ' + (x && x.stack ? x.stack.split('\n').slice(0, 3).join(' | ') : x)); } }
const near = (a, b, tol) => Math.abs(a - b) <= (tol || 0.6);

/* 허상 */
T('mirrorlance', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['mirrorlance']); const e = b.en[0]; e.haze = 1; const d = hit(b, e, 100); ok(near(d, 30, 1) && e.haze === 0, '신기루 창: 허상을 걷어도 30%가 들어간다 (' + d + ')'); });
T('gazebow', () => { const b = battle({ en: [['bruiser', 0]] }, 'hunter', 13, ['gazebow']); const e = b.en[0]; e.haze = 1; b.p.focus = { id: e.id, n: 2 }; const d = hit(b, e, 100, { id: 'basic', ranged: 1 }, { single: 1 }); ok(e.haze === 1 && d > 90, '응시하는 활: 추적 2겹이면 허상을 꿰뚫는다 (' + d + ', 허상 ' + e.haze + ')'); });
T('glassknife', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['glassknife']); const e = b.en[0]; e.haze = 1; b.p.st = 40; hit(b, e, 50); ok(b.p.st === 46 && e.haze === 0, '깨진 거울 칼: 허상을 걷으면 스태미나 +6 (' + b.p.st + ')'); });
T('hazeking', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['hazeking']); const e = b.en[0]; e.haze = 1; const d = hit(b, e, 100); ok(near(d, 62.5, 1.5), '신기루 왕의 대검: 50% × 1.25 (' + d + ')'); });
T('kiamulet3', () => { const b = battle({ en: [['bruiser', 0]] }, 'monk', 13, ['kiamulet3']); const e = b.en[0]; e.haze = 1; G0.addS(b, b.p, 'empower', 1); const d = hit(b, e, 100); ok(e.haze === 1 && d > 60, '기 모으는 목걸이: 기를 실은 공격은 허상을 걷지 않고 지나간다 (' + d + ', 허상 ' + e.haze + ')'); });
T('shadowsickle', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0]] }, 'assassin', 13, ['shadowsickle']); const e = b.en[0]; e.haze = 1; b.actN = 5; G0.fxRun(b.p, 'onParry', b, b.p, b.en[1]); const d = hit(b, e, 100); ok(e.haze === 1 && d > 60, '그림자 낫: 흘린 뒤 첫 공격은 허상을 꿰뚫는다 (' + d + ')'); const e2 = b.en[1]; e2.haze = 1; hit(b, e2, 100); ok(e2.haze === 0, '그림자 낫: 효과는 한 행동뿐 (허상 ' + e2.haze + ')'); });
T('hazering', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['hazering']); const e = b.en[0]; e.haze = 1; hit(b, e, 10); const d0 = hit(b, e, 100); const b2 = battle({ en: [['bruiser', 0]] }, 'assassin', 13, []); const e2 = b2.en[0]; e2.haze = 1; hit(b2, e2, 10); const d1 = hit(b2, e2, 100); ok(near(d0 / d1, 1.08, 0.01), '신기루 반지: 허상을 걷은 라운드에 +8% (' + (d0 / d1).toFixed(3) + ')'); });
T('veilblade', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0]] }, 'assassin', 13, ['veilblade']); b.en[0].haze = 1; hit(b, b.en[0], 10); const d = hit(b, b.en[1], 100); const b2 = battle({ en: [['bruiser', 0], ['bruiser', 0]] }, 'assassin', 13, []); const d2 = hit(b2, b2.en[1], 100); ok(near(d / d2, 1.15, 0.01), '베일 가르는 칼: 다음 행동 +15% (' + (d / d2).toFixed(3) + ')'); const d3 = hit(b, b.en[1], 100); ok(near(d3 / d2, 1, 0.01) || d3 > 0, '베일 가르는 칼: 한 행동뿐'); });
T('hazebind', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['haze'] }, 'assassin', 13, ['hazebind']); ok(b.en.every(e => e.haze === 1), '아지랑이 방은 허상으로 시작'); G0.fxRun(b.p, 'onAct', b, b.p, 'basic', {}, null); ok(b.en.every(e => !(e.haze > 0)) && b.p.ward >= 0, '허상 엮는 반지: 첫 행동에 허상이 한 겹 걷힌다 (' + b.en.map(e => e.haze).join(',') + ')'); });
T('mirage_hand', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0]] }, 'assassin', 13, ['mirage_hand']); b.p.ward = 0; const e = b.en[0]; const h0 = b.p.hp; G0.hurtPlayer(b, 20, { src: e, single: 1, label: '시험' }); ok(b.p.hp === h0, '신기루의 손: 라운드의 첫 한 적 대상 공격은 헛친다'); G0.hurtPlayer(b, 20, { src: e, single: 1, label: '시험' }); ok(b.p.hp < h0, '신기루의 손: 두 번째는 들어온다'); });
T('mirageplate', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['mirageplate']); b.p.ward = 0; const h0 = b.p.hp; G0.hurtPlayer(b, 20, { src: b.en[0], single: 1, label: '시험' }); ok(b.p.hp === h0, '신기루 판금: 처음 받는 직접 피해는 허상이 맞는다'); G0.hurtPlayer(b, 20, { src: b.en[0], single: 1, label: '시험' }); ok(b.p.hp < h0, '신기루 판금: 한 번뿐'); });
/* 붕대 */
T('burnscythe', () => { const b = battle({ en: [['wrapped', 0], ['bruiser', 0]] }, 'assassin', 13, ['burnscythe']); const e = b.en[0]; ok(e.wrap === 3, '붕대 3'); const k0 = e.brk; G0.addS(b, e, 'ignite', 1); ok(!e.wrap && e.brk >= k0 + 10, '불사르는 낫: 붕대가 타면 붕괴 +10 (' + (e.brk - k0) + ')'); });
T('unravel', () => { const b = battle({ en: [['wrapped', 0], ['wrapped', 0], ['bruiser', 0]] }, 'assassin', 13, ['unravel']); G0.addS(b, b.en[0], 'ignite', 1); ok(!b.en[0].wrap && !b.en[1].wrap, '풀어 헤치는 칼: 붕대 하나가 벗겨지면 다른 붕대도 풀린다 (' + b.en[0].wrap + ',' + b.en[1].wrap + ')'); ok(G0.st(b.en[0], 'vuln') === 2, '풀어 헤치는 칼: 취약 2'); });
T('wearinggrip', () => { const b = battle({ en: [['wrapped', 0]] }, 'assassin', 13, ['wearinggrip']); const e = b.en[0]; hit(b, e, 10); ok(e.wrap === 1, '닳게 하는 손: 한 번 맞았는데 붕대가 둘 닳는다 (' + e.wrap + ')'); });
T('cinderaxe', () => { const b = battle({ en: [['wrapped', 0]] }, 'assassin', 13, ['cinderaxe']); const e = b.en[0]; b.p.st = 40; hit(b, e, 10); ok(!e.wrap && b.p.st === 48, '붕대 사르는 도끼: 붕대를 태우고 스태미나 +8 (' + e.wrap + ', ' + b.p.st + ')'); });
T('wrapripper', () => { const mk = it => { const b = battle({ en: [['wrapped', 0]] }, 'assassin', 13, it); return hit(b, b.en[0], 100); }; const r = mk(['wrapripper']) / mk([]); ok(near(r, 1.12, 0.01), '붕대 푸는 쇠갈고리: 붕대 감긴 적에게 +12% (' + r.toFixed(3) + ')'); });
T('poisonwrap', () => { const b = battle({ en: [['wrapped', 0], ['wrapped', 0]] }, 'assassin', 13, ['poisonwrap']); G0.fxRun(b.p, 'onSkill', b, b.p, { id: 'x', s: { fx: [{ k: 'burst' }] } }); ok(b.en.every(e => !e.wrap), '독 삼킨 장갑: 독을 터뜨리면 붕대가 모두 풀린다'); });
T('wrapmail', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['wrapmail']); b.p.ward = 0; const e = b.en[0]; const hp = () => b.p.hp; const base = battle({ en: [['bruiser', 0]] }, 'assassin', 13, []); base.p.ward = 0; const h0 = base.p.hp; G0.hurtPlayer(base, 30, { src: base.en[0], single: 1, label: '시험' }); const lost0 = h0 - base.p.hp; const h1 = hp(); G0.hurtPlayer(b, 30, { src: e, single: 1, label: '시험' }); const lost1 = h1 - hp(); ok(near(lost1 / lost0, 0.7, 0.02), '굳은 붕대 갑옷: 붕대가 감긴 동안 −30% (' + (lost1 / lost0).toFixed(3) + ')'); });
T('mirrorarmor', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['mirrorarmor']); b.p.ward = 0; const e = b.en[0]; e.haze = 1; e.wrap = 3; const hp0 = e.hp; G0.hurtPlayer(b, 40, { src: e, single: 1, label: '시험' }); ok(e.hp < hp0 && e.haze === 1 && e.wrap === 3, '거울 갑옷: 때린 적에게 되돌린다, 허상 · 붕대는 지나간다 (' + (hp0 - e.hp).toFixed(1) + ')'); });
/* 열기 */
T('heatcut', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'warden', 13, ['coolplate']); b.heat = 90; let n = 0; for (let i = 0; i < 12; i++) { b.actN++; G0.fxRun(b.p, 'onAct', b, b.p, 'guard', {}, null); n++; } ok(b.heat === 70, '서늘한 흉갑: 장비로 내리는 열기는 전투마다 20까지 (' + b.heat + ')'); });
T('heatcut2', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'warden', 13, ['coolplate', 'wetrobe']); b.heat = 90; for (let i = 0; i < 8; i++) { G0.fxRun(b.p, 'onAct', b, b.p, 'guard', {}, null); G0.fxRun(b.p, 'onRound', b, b.p); } ok(b.heat === 70, '열기를 내리는 장비 둘이어도 합쳐 20까지 (' + b.heat + ')'); });
T('stormplate', () => { const mk = it => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'assassin', 13, it); b.p.ward = 0; b.heat = 100; b.heatWarn = b.round; const h0 = b.p.hp; G0.heatStorm(b); return [h0 - b.p.hp, b.p.ward]; }; const [l1, w1] = mk(['stormplate']); const [l0] = mk([]); ok(l1 < l0 * 0.8 + 0.01, '열풍 막이 판금: 열풍 피해 −30%에 보호막 +10 (' + l1.toFixed(1) + ' / ' + l0.toFixed(1) + ', 남은 보호막 ' + w1 + ')'); });
T('windwrap', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0]], mods: ['noon'] }, 'assassin', 13, ['windwrap']); b.heat = 100; b.heatWarn = b.round; b.actN = 3; G0.heatStorm(b); b.actN = 4; const d = hit(b, b.en[1], 100); const b2 = battle({ en: [['bruiser', 0], ['bruiser', 0]], mods: ['noon'] }, 'assassin', 13, []); b2.heat = 100; b2.heatWarn = b2.round; b2.actN = 3; G0.heatStorm(b2); b2.actN = 4; const d2 = hit(b2, b2.en[1], 100); ok(near(d / d2, 1.2, 0.02), '열풍 감는 손: 열풍이 분 뒤 +20% (' + (d / d2).toFixed(3) + ')'); });
T('stormbreaker', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'warden', 13, ['stormbreaker']); b.heat = 99; b.heatWarn = b.round || 0; const d = hit(b, b.en[0], 100); b.heat = 50; const b2 = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'warden', 13, []); const d2 = hit(b2, b2.en[0], 100); ok(near(d / d2, 1.2, 0.02), '열풍 가르는 도끼: 열풍이 예고된 동안 +20% (' + (d / d2).toFixed(3) + ')'); const h = b.heat; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.heat === h + 2, '열풍 가르는 도끼: 대가로 열기 +2'); });
T('sunbind', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['noon'] }, 'assassin', 13, ['sunbind']); b.heat = 45; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.en.every(e => G0.st(e, 'ignite') === 1) && b.heat === 48, '해 묶는 목걸이: 열기 40 이상이면 적 모두 화상 1, 열기 +3 (' + b.heat + ')'); });
T('noon-ring', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'assassin', 13, ['noonring']); b.p.st = 40; b.heat = 100; b.heatWarn = b.round; G0.heatStorm(b); ok(b.p.st >= 49, '한낮 반지: 열풍이 불면 스태미나 +10 (' + b.p.st + ')'); });
/* 화상 */
T('ashscale', () => { const mk = it => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, it); b.p.ward = 0; b.p.s.ignite = { stacks: 4, until: 9999, dur: 9999 }; const h0 = b.p.hp; G0.hurtPlayer(b, 10, { src: b.en[0], single: 1, label: '시험' }); return h0 - b.p.hp; }; const a = mk(['ashscale']), z = mk([]); ok(z - a > 0.9 && z - a < 1.1, '재 비늘 갑옷: 화상 추가 피해 4 → 3 (' + z.toFixed(2) + ' / ' + a.toFixed(2) + ')'); });
T('burntname', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['burntname']); const e = b.en[0]; G0.addS(b, e, 'ignite', 4); const d = hit(b, e, 10); ok(near(d, 10, 0.5), '불사른 이름의 검: 화상이 직접 피해에 더해지지 않는다 (' + d + ')'); const h0 = e.hp; G0.fxRun(b.p, 'onRound', b, b.p); ok(e.hp < h0 && G0.st(e, 'ignite') === 2, '불사른 이름의 검: 라운드가 끝나면 화상이 한 번 타오른다 (' + (h0 - e.hp).toFixed(1) + ', 화상 ' + G0.st(e, 'ignite') + ')'); });
T('ashpact', () => { const b = battle({ en: [['bruiser', 1]] }, 'assassin', 13, ['ashpact']); const e = b.en[0]; e.fire = 1; b.p.ward = 0; G0.fireCarry(b, e, 0, true); ok(G0.st(e, 'ignite') >= 1 && G0.st(b.p, 'ignite') >= 1, '재의 서약 반지: 나를 불붙인 적에게 화상을 돌려준다 (' + G0.st(e, 'ignite') + ')'); });
T('emberfeeder', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['emberfeeder']); b.p.s.ignite = { stacks: 2, until: 9999, dur: 9999 }; b.actN = 3; G0.fxRun(b.p, 'onRound', b, b.p); ok(G0.st(b.p, 'ignite') === 1, '불씨 먹는 검: 화상을 하나 먹는다'); b.actN = 4; const d = hit(b, b.en[0], 100); const b2 = battle({ en: [['bruiser', 0]] }, 'assassin', 13, []); const d2 = hit(b2, b2.en[0], 100); ok(near(d / d2, 1.12, 0.02), '불씨 먹는 검: 다음 공격 +12% (' + (d / d2).toFixed(3) + ')'); });
T('sunscorch', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['sunscorch']); const e = b.en[0]; G0.addS(b, e, 'ignite', 6); const h0 = e.hp; const d = hit(b, e, 10); ok(d > 10 + 20 && !G0.st(e, 'ignite'), '정오의 칼날: 화상 6을 한꺼번에 태운다 (' + d.toFixed(1) + ')'); });
T('pyrerobe', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]] }, 'assassin', 13, ['pyrerobe']); b.p.s.ignite = { stacks: 3, until: 9999, dur: 9999 }; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.en.every(e => G0.st(e, 'ignite') === 1), '분신의 법의: 화상 3 이상이면 적 모두 화상 1'); });
T('ashskin', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['ashskin']); b.p.ward = 0; b.p.s.ignite = { stacks: 4, until: 9999, dur: 9999 }; const h0 = b.p.hp; G0.hurtPlayer(b, 10, { src: b.en[0], single: 1, label: '시험' }); ok(near(h0 - b.p.hp, 10 * 0.5 * 0 + (h0 - b.p.hp), 99) && h0 - b.p.hp < 10.01, '재가 된 살갗: 화상이 추가 피해를 주지 않는다 (' + (h0 - b.p.hp).toFixed(2) + ')'); const d = hit(b, b.en[0], 100); const b2 = battle({ en: [['bruiser', 0]] }, 'assassin', 13, []); const d2 = hit(b2, b2.en[0], 100); ok(d / d2 > 1.11, '재가 된 살갗: 화상 한 칸마다 주는 피해 +4% (' + (d / d2).toFixed(3) + ')'); });
T('shieldknuckle', () => { const b = battle({ en: [['bruiser', 1]] }, 'warden', 13, ['shieldknuckle']); b.p.ward = 10; G0.addS(b, b.p, 'ignite', 2); ok(!G0.st(b.p, 'ignite'), '막 주먹: 보호막이 있는 동안 화상이 걸리지 않는다'); b.p.ward = 0; G0.addS(b, b.p, 'ignite', 2); ok(G0.st(b.p, 'ignite') === 2, '막 주먹: 보호막이 없으면 걸린다'); });
T('snuffgloves', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['snuffgloves']); const e = b.en[0]; e.fireNext = 2; hit(b, e, 10); ok(!e.fireNext, '불씨 끄는 장갑: 받은 불씨가 꺼진다'); });
/* 잠복 · 모래폭풍 */
T('surgesabre', () => { const b = battle({ en: [['lurker', 0], ['bruiser', 0]] }, 'assassin', 13, ['surgesabre']); const e = b.en[0]; G0.fxRun(b.p, 'onParry', b, b.p, e); ok(G0.st(e, 'vuln') === 2, '솟구침 받아치는 곡도: 흘린 잠복자에게 취약 2'); G0.fxRun(b.p, 'onEvade', b, b.p, b.en[1]); ok(!G0.st(b.en[1], 'vuln'), '잠복자가 아니면 걸리지 않는다'); });
T('surfacespear', () => { const mk = it => { const b = battle({ en: [['lurker', 0]] }, 'assassin', 13, it); const e = b.en[0]; e.under = 0; G0.addS(b, e, 'vuln', 2); return hit(b, e, 100); }; const r = mk(['surfacespear']) / mk([]); ok(near(r, 1.2, 0.01), '드러난 자의 창: 드러난 잠복자에게 +20% (' + r.toFixed(3) + ')'); });
T('duststaff', () => { const mk = it => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['sandstorm'] }, 'assassin', 13, it); return hit(b, b.en[1], 100); }; const r = mk(['duststaff']) / mk([]); ok(near(r, 1.15, 0.01), '먼지 바람 지팡이: 모래폭풍 방 후열 +15% (' + r.toFixed(3) + ')'); });
T('dunemail', () => { const b = battle({ en: [['lurker', 0]] }, 'warden', 13, ['dunemail']); b.p.ward = 0; G0.fxRun(b.p, 'onParry', b, b.p, b.en[0]); ok(b.p.ward > 0, '모래 갑주: 솟구침을 흘리면 보호막'); });
/* 일반 */
T('doublebrand', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['doublebrand']); const e = b.en[0]; b.cur = { id: 'basic' }; G0.addS(b, e, 'bleed', 1); b.cur = null; ok(G0.st(e, 'bleed') === 2, '겹낙인: 내가 거는 출혈이 1 더 걸린다 (' + G0.st(e, 'bleed') + ')'); G0.addS(b, b.p, 'weak', 1); ok(G0.st(b.p, 'weak') === 2, '겹낙인: 내게 걸리는 약화도 1 더 (' + G0.st(b.p, 'weak') + ')'); });
T('phoenixring', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]] }, 'warden', 13, ['phoenixring']); b.p.ward = 0; b.p.hp = 5; G0.hurtPlayer(b, 999, { src: b.en[0], single: 1, label: '시험' }); ok(b.p.hp > b.p.hpMax * 0.4 && !b.over && b.en.every(e => G0.st(e, 'ignite') >= 4), '재에서 일어나는 반지: 쓰러질 때 생명력 절반으로 일어난다 (' + Math.round(b.p.hp) + ')'); b.p.hp = 5; G0.hurtPlayer(b, 999, { src: b.en[0], single: 1, label: '시험' }); ok(b.over === 'lose' || b.p.hp <= 0, '재에서 일어나는 반지: 한 런에 한 번뿐'); });
T('afterglow', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0], ['archer', 0]] }, 'assassin', 13, ['afterglow']); const e = b.en[0]; G0.addS(b, e, 'ignite', 4); G0.addS(b, e, 'bleed', 3); e.hp = 1; hit(b, e, 50); ok(!e.alive && b.en.slice(1).every(x => G0.st(x, 'ignite') === 2 && G0.st(x, 'bleed') === 2), '잔광의 목걸이: 쓰러진 적의 상태 절반이 남은 적에게 번진다 (' + G0.st(b.en[1], 'ignite') + ',' + G0.st(b.en[1], 'bleed') + ')'); });
T('firstlight', () => { const mk = it => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, it); const e = b.en[0]; const d1 = hit(b, e, 50); const d2 = hit(b, e, 50); return [d1, d2]; }; const [a1, a2] = mk(['firstlight']); const [z1, z2] = mk([]); ok(near(a1 / z1, 1.3, 0.02) && near(a2 / z2, 0.95, 0.02), '첫 빛의 목걸이: 첫 피해 +30%, 그 뒤 −5% (' + (a1 / z1).toFixed(3) + ', ' + (a2 / z2).toFixed(3) + ')'); });
T('cullingaxe', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['cullingaxe']); const e = b.en[0]; const d1 = hit(b, e, 10); e.hp = e.hpMax * 0.1; const d2 = hit(b, e, 10); ok(near(d1, 9, 0.2) && near(d2, 13, 0.2), '솎아 베는 도끼: 가득 찬 적 −10%, 20% 이하 +30% (' + d1 + ', ' + d2 + ')'); });
T('triplering', () => { const mk = it => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, it); const e = b.en[0]; G0.addPoison(b, e, 2, 1); G0.addS(b, e, 'bleed', 2); G0.addS(b, e, 'ignite', 1); e.s.ignite = { stacks: 0, until: 9999, dur: 9999 }; delete e.s.ignite; G0.addS(b, e, 'ignite', 1); const d = hit(b, e, 100); return d; }; ok(mk(['triplering']) > 0, '세 겹 반지 실행'); });
T('eyeofnoon', () => { const mk = it => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, it); b.en[0].intent = { k: 'heavy' }; return hit(b, b.en[0], 100); }; const r = mk(['eyeofnoon']) / mk([]); ok(near(r, 1.2, 0.02), '정오의 눈: 큰 공격이 예고되면 +20% (' + r.toFixed(3) + ')'); });
T('soloring', () => { const mk = it => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, it); return hit(b, b.en[0], 100); }; const r = mk(['soloring']) / mk([]); ok(near(r, 1.1, 0.01), '마지막 한 명의 반지: 적이 하나면 +10% (' + r.toFixed(3) + ')'); });
T('oasis_gourd', () => { const b = battle({ en: [['bruiser', 0]] }, 'warden', 13, ['oasis_gourd']); b.p.flask.life = G0.flaskCap(b.p, 'life'); const c0 = b.p.flask.life; b.p.hp = b.p.hpMax * 0.5; G0.playerAct(b, 'flaskL', null); const c1 = b.p.flask.life; ok(c1 === c0, '오아시스 호리병: 첫 모금은 충전을 쓰지 않는다 (' + c0 + ' → ' + c1 + ')'); b.p.st = b.p.stMax; G0.playerAct(b, 'flaskL', null); ok(b.p.flask.life === c1 - 1 || b.over, '두 번째는 쓴다 (' + b.p.flask.life + ')'); });
T('hazebottle', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0]], mods: ['haze'] }, 'warden', 13, ['hazebottle']); G0.playerAct(b, 'flaskM', null); ok(b.en.every(e => !(e.haze > 0)), '신기루 병: 정화 플라스크가 허상을 모두 걷는다'); });
T('wardfont', () => { const b = battle({ en: [['bruiser', 0]] }, 'warden', 13, ['wardfont']); b.p.ward = 0; G0.playerAct(b, 'flaskM', null); ok(b.p.ward >= G0.wardMax(b.p) * 0.45, '보호막 샘: 정화 플라스크가 보호막을 절반까지 채운다 (' + Math.round(b.p.ward) + '/' + G0.wardMax(b.p) + ')'); });
T('scapeflask', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]] }, 'warden', 13, ['scapeflask']); G0.addS(b, b.p, 'ignite', 4); G0.playerAct(b, 'flaskM', null); ok(!G0.st(b.p, 'ignite') && b.en.every(e => G0.st(e, 'ignite') >= 2), '속죄양 병: 내 화상을 적에게 절반씩 나눠 건다'); });
T('mirrorshock', () => { const b = battle({ en: [['bruiser', 0]] }, 'elementalist', 13, ['mirrorshock']); const e = b.en[0]; e.haze = 1; G0.fxRun(b.p, 'onShock', b, b.p, e); ok(e.haze === 0, '거울 충격 반지: 열충격이 허상을 한 겹 걷는다'); const k0 = e.brk; G0.fxRun(b.p, 'onShock', b, b.p, e); ok(e.brk > k0, '허상이 없으면 붕괴 +4'); });
T('stormbeads', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['sandstorm'] }, 'warden', 13, ['stormbeads']); b.p.ward = 0; const e = b.en[0]; e.hp = 1; hit(b, e, 50); ok(b.p.ward >= 10, '폭풍 묵주: 전열이 모두 쓰러지면 보호막 +10 (' + b.p.ward + ')'); });
T('kilnring', () => { const mk = it => { const b = battle({ en: [['bruiser', 0]], mods: ['brazier'] }, 'assassin', 13, it); G0.addS(b, b.en[0], 'ignite', 4); return hit(b, b.en[0], 10); }; const a = mk(['kilnring']), z = mk([]); ok(near((a - 10) / (z - 10), 1.2, 0.02), '가마 반지: 불씨 화로 방에서 화상 추가 피해 +20% (' + z.toFixed(2) + ' → ' + a.toFixed(2) + ')'); });
console.log('3챕터 장비 점검: 통과 ' + pass + ', 실패 ' + fail); process.exitCode = fail ? 1 : 0;
