/* 3챕터 장비 효과 점검 (10월 8일, docs/아이템/3챕터-장비.md 8절): 06a2의 게임 코드를 vm에서 그대로 돌려, 장비의 새 지점과 핵심 효과가 문장대로 일어나는지 장면마다 확인한다.
   itemcheck는 "발동했는가"를 세고, 이 점검은 "문장대로 바뀌었는가"를 본다. 실패 0이어야 한다.
   실행: DGDIR=06a2 node tools/item3check.js */
process.env.DGDIR = process.env.DGDIR || '06a2';
const D = require('./dgqa.js'); const G0 = D.G0; const run_ = D.run_;
let fail = 0, pass = 0; const ok = (c, m) => { if (c) pass++; else { fail++; console.log('실패:', m); } };
const V = k => run_(k);
function battle(room, build, lv, items) {
  const bd = build || 'warden';
  const p = G0.mkPlayer(bd, {}, G0.statRecommend(bd, {}, 15 + 2 * ((lv || 13) - 1)), G0.TREE2[bd].starters); p.lv = lv || 13;
  for (const k of items || []) p.eq[G0.ITEMS[k].slot] = k;
  p.stat.wil = 0; G0.applyStats(p, p.stat || {}); p.hp = p.hpMax; p.st = p.stMax;
  const r = Object.assign({ ch: 3, lv: 11, floor: 14, names: V('ENEMY_NAMES[3]'), path: 'main', en: [] }, room);
  const b = G0.roomBattle(p, r, r.boss ? 'queen' : null, 7); b.stepMode = false; for (const e of b.en) { e.hpMax = 100000; e.hp = 100000; } return b; /* 한 번에 쓰러지지 않게 생명력을 부풀린다 */
}
const al = b => G0.alive(b);
/* 한 번 친다: 행동 번호를 올리고 b.cur를 두고 hurtEnemy를 부른다 */
function hit(b, e, raw, cur, o) { b.actN = (b.actN || 0) + 1; b.cur = cur || { id: 'basic' }; const h0 = e.hp; G0.hurtEnemy(b, e, raw, o || { single: 1, melee: 1 }); b.cur = null; return h0 - e.hp; }
function T(name, f) { try { f(); } catch (x) { ok(false, name + ' 예외: ' + (x && x.stack ? x.stack.split('\n').slice(0, 3).join(' | ') : x)); } }
const near = (a, b, tol) => Math.abs(a - b) <= (tol || 0.6);

/* 풀: 세 풀의 장비 id가 겹치지 않는다(겹치면 데이터가 서로 덮는다), 3챕터 풀은 200종 */
T('pools', () => { const P = [V('CH1_POOL'), V('CH2_POOL'), V('CH3_POOL')]; const all = [].concat(...P); ok(new Set(all).size === all.length, '세 풀의 장비 id가 겹친다: ' + all.filter((k, i) => all.indexOf(k) !== i).join(', ')); ok(P[2].length === 200, '3챕터 풀 ' + P[2].length + '종'); ok(P[2].every(k => V('IFX["' + k + '"]')), '효과가 없는 3챕터 장비'); });
/* 드롭: 3챕터 등급 확률, 같은 전설은 한 런에 한 번, 전설이 떨어지면 영웅으로 바꾼다 */
T('drops', () => {
  const tally = (src, n) => { const c = { n: 0, m: 0, r: 0, h: 0, l: 0 }; for (let i = 0; i < n; i++) c[G0.rollGradeCh(3, src)]++; return c; };
  const rm = tally('room', 200000); const near2 = (v, t, tol) => Math.abs(v / 2000 - t) <= tol;
  ok(near2(rm.n, 50, 1) && near2(rm.m, 32, 1) && near2(rm.r, 14, 0.7) && near2(rm.h, 3.4, 0.4) && near2(rm.l, 0.6, 0.2), '3챕터 일반 · 매복 등급 확률 ' + JSON.stringify(rm));
  const bg = tally('big', 100000); ok(bg.n === 0 && bg.m === 0 && Math.abs(bg.h / 1000 - 10) < 1 && Math.abs(bg.l / 1000 - 2) < 0.6, '3챕터 강적 · 시련 · 보물: 희귀 이상만 ' + JSON.stringify(bg));
  const bs = tally('boss', 100000); ok(bs.n === 0 && bs.m === 0 && Math.abs(bs.h / 1000 - 32) < 1.5 && Math.abs(bs.l / 1000 - 8) < 1, '3챕터 보스: 희귀 이상만 ' + JSON.stringify(bs));
  const p = battle({ en: [['bruiser', 0]] }, 'assassin', 13, []).p; const run = { p, ch: 3, inv: {}, legSeen: [] }; const L3 = V('CH3_POOL'); const got = []; for (let i = 0; i < 12; i++) got.push(G0.dropKey(run, 'l'));
  const legs = got.filter(k => G0.ITEMS[k].g === 'l');
  ok(legs.length === 8 && new Set(legs).size === 8 && legs.every(k => L3.includes(k)), '같은 전설은 한 런에 한 번: 3챕터 전설 8종이 하나씩 (' + legs.length + '종)');
  ok(got.slice(8).every(k => G0.ITEMS[k].g === 'h' && L3.includes(k)), '전설이 떨어지면 영웅으로 바뀐다');
  const old = []; for (let i = 0; i < 3000; i++) old.push(G0.dropKey({ p, ch: 3, inv: {}, legSeen: [] }, 'm')); const share = old.filter(k => !L3.includes(k)).length / old.length; ok(share > 0.07 && share < 0.13 && old.filter(k => !L3.includes(k)).every(k => V('CH2_POOL').includes(k)), '고급 드롭의 10%는 2챕터 풀 (' + share.toFixed(3) + ')');
});
/* 허상 */
T('mirrorlance', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['mirrorlance']); const e = b.en[0]; e.haze = 1; const d = hit(b, e, 100); ok(near(d, 30, 1) && e.haze === 0, '신기루 창: 허상을 걷어도 30%가 들어간다 (' + d + ')'); });
T('gazebow', () => { const b = battle({ en: [['bruiser', 0]] }, 'hunter', 13, ['gazebow']); const e = b.en[0]; e.haze = 1; b.p.focus = { id: e.id, n: 2 }; const d = hit(b, e, 100, { id: 'basic', ranged: 1 }, { single: 1 }); ok(e.haze === 1 && d > 90, '응시하는 활: 추적 2겹이면 허상을 꿰뚫는다 (' + d + ', 허상 ' + e.haze + ')'); });
T('glassknife', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['glassknife']); const e = b.en[0]; e.haze = 1; b.p.st = 40; hit(b, e, 50); ok(b.p.st === 46 && e.haze === 0, '깨진 거울 칼: 허상을 걷으면 스태미나 +6 (' + b.p.st + ')'); });
T('hazeking', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['hazeking']); const e = b.en[0]; e.haze = 1; const d = hit(b, e, 100); ok(near(d, 62.5, 1.5), '신기루 왕의 대검: 50% × 1.25 (' + d + ')'); });
T('kiamulet3', () => { const b = battle({ en: [['bruiser', 0]] }, 'monk', 13, ['kiamulet3']); const e = b.en[0]; e.haze = 1; G0.addS(b, b.p, 'empower', 1); const d = hit(b, e, 100); ok(e.haze === 1 && d > 60, '기 모으는 목걸이: 기를 실은 공격은 허상을 걷지 않고 지나간다 (' + d + ', 허상 ' + e.haze + ')'); });
T('shadowsickle', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0]] }, 'assassin', 13, ['shadowsickle']); const e = b.en[0]; e.haze = 1; b.actN = 5; G0.fxRun(b.p, 'onParry', b, b.p, b.en[1]); const d = hit(b, e, 100); ok(e.haze === 1 && d > 60, '그림자 낫: 흘린 뒤 첫 공격은 허상을 꿰뚫는다 (' + d + ')'); const e2 = b.en[1]; e2.haze = 1; hit(b, e2, 100); ok(e2.haze === 0, '그림자 낫: 효과는 한 행동뿐 (허상 ' + e2.haze + ')'); });
T('hazering', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['hazering']); const e = b.en[0]; e.haze = 1; hit(b, e, 10); const d0 = hit(b, e, 100); const b2 = battle({ en: [['bruiser', 0]] }, 'assassin', 13, []); const e2 = b2.en[0]; e2.haze = 1; hit(b2, e2, 10); const d1 = hit(b2, e2, 100); ok(near(d0 / d1, 1.08, 0.01), '신기루 반지: 허상을 걷은 라운드에 +8% (' + (d0 / d1).toFixed(3) + ')'); });
T('veilblade', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0]] }, 'assassin', 13, ['veilblade']); b.en[0].haze = 1; hit(b, b.en[0], 10); const d = hit(b, b.en[1], 100); const b2 = battle({ en: [['bruiser', 0], ['bruiser', 0]] }, 'assassin', 13, []); const d2 = hit(b2, b2.en[1], 100); ok(near(d / d2, 1.15, 0.01), '베일 가르는 칼: 다음 행동 +15% (' + (d / d2).toFixed(3) + ')'); const d3 = hit(b, b.en[1], 100); ok(near(d3 / d2, 1, 0.01), '베일 가르는 칼: 한 행동뿐'); });
T('hazebind', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['haze'] }, 'assassin', 13, ['hazebind']); ok(b.en.every(e => e.haze === 1), '아지랑이 방은 허상으로 시작'); G0.fxRun(b.p, 'onAct', b, b.p, 'basic', {}, null); ok(b.en.every(e => !(e.haze > 0)) && b.p.ward >= 0, '허상 엮는 반지: 첫 행동에 허상이 한 겹 걷힌다 (' + b.en.map(e => e.haze).join(',') + ')'); });
T('mirage_hand', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0]] }, 'assassin', 13, ['mirage_hand']); b.p.ward = 0; const e = b.en[0]; const h0 = b.p.hp; G0.hurtPlayer(b, 20, { src: e, single: 1, label: '시험' }); G0.hurtPlayer(b, 20, { src: e, single: 1, label: '시험' }); ok(b.p.hp === h0, '신기루의 손: 허상 2겹이 한 적 대상 공격 둘을 헛치게 한다'); G0.hurtPlayer(b, 20, { src: e, single: 1, label: '시험' }); ok(b.p.hp < h0, '신기루의 손: 셋째는 들어온다'); b.en[1].haze = 1; hit(b, b.en[1], 10); const h1 = b.p.hp; G0.hurtPlayer(b, 20, { src: e, single: 1, label: '시험' }); ok(b.p.hp === h1, '신기루의 손: 적의 허상을 걷으면 내 허상이 한 겹 생긴다'); });
T('mirageplate', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['mirageplate']); b.p.ward = 0; const h0 = b.p.hp; G0.hurtPlayer(b, 20, { src: b.en[0], single: 1, label: '시험' }); ok(b.p.hp === h0, '신기루 판금: 처음 받는 직접 피해는 허상이 맞는다'); G0.hurtPlayer(b, 20, { src: b.en[0], single: 1, label: '시험' }); ok(b.p.hp < h0, '신기루 판금: 한 번뿐'); });
/* 붕대 */
T('burnscythe', () => { const b = battle({ en: [['wrapped', 0], ['bruiser', 0]] }, 'assassin', 13, ['burnscythe']); const e = b.en[0]; ok(e.wrap === 3, '붕대 3'); const k0 = e.brk; G0.addS(b, e, 'ignite', 1); ok(!e.wrap && e.brk >= k0 + 10, '불사르는 낫: 붕대가 타면 붕괴 +10 (' + (e.brk - k0) + ')'); });
T('unravel', () => { const b = battle({ en: [['wrapped', 0], ['wrapped', 0], ['bruiser', 0]] }, 'assassin', 13, ['unravel']); G0.addS(b, b.en[0], 'ignite', 1); ok(!b.en[0].wrap && !b.en[1].wrap, '풀어 헤치는 칼: 붕대 하나가 벗겨지면 다른 붕대도 풀린다 (' + b.en[0].wrap + ',' + b.en[1].wrap + ')'); ok(G0.st(b.en[0], 'vuln') === 2, '풀어 헤치는 칼: 취약 2'); });
T('wearinggrip', () => { const b = battle({ en: [['wrapped', 0]] }, 'assassin', 13, ['wearinggrip']); const e = b.en[0]; hit(b, e, 10); ok(e.wrap === 1, '닳게 하는 손: 한 번 맞았는데 붕대가 둘 닳는다 (' + e.wrap + ')'); });
T('cinderaxe', () => { const b = battle({ en: [['wrapped', 0]] }, 'assassin', 13, ['cinderaxe']); const e = b.en[0]; b.p.st = 40; hit(b, e, 10); ok(!e.wrap && b.p.st === 48, '붕대 사르는 도끼: 붕대를 태우고 스태미나 +8 (' + e.wrap + ', ' + b.p.st + ')'); });
T('wrapripper', () => { const mk = it => { const b = battle({ en: [['wrapped', 0]] }, 'assassin', 13, it); return hit(b, b.en[0], 100); }; const r = mk(['wrapripper']) / mk([]); ok(near(r, 1.12, 0.01), '붕대 푸는 쇠갈고리: 붕대 감긴 적에게 +12% (' + r.toFixed(3) + ')'); });
T('poisonwrap', () => { const b = battle({ en: [['wrapped', 0], ['wrapped', 0]] }, 'assassin', 13, ['poisonwrap']); G0.fxRun(b.p, 'onSkill', b, b.p, { id: 'x', s: { fx: [{ k: 'burst' }] } }); ok(b.en.every(e => !e.wrap), '독 삼킨 장갑: 독을 터뜨리면 붕대가 모두 풀린다'); });
T('wrapmail', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['wrapmail']); b.p.ward = 0; const e = b.en[0]; const hp = () => b.p.hp; const base = battle({ en: [['bruiser', 0]] }, 'assassin', 13, []); base.p.ward = 0; const h0 = base.p.hp; G0.hurtPlayer(base, 30, { src: base.en[0], single: 1, label: '시험' }); const lost0 = h0 - base.p.hp; const h1 = hp(); G0.hurtPlayer(b, 30, { src: e, single: 1, label: '시험' }); const lost1 = h1 - hp(); ok(near(lost1 / lost0, 0.7, 0.02), '굳은 붕대 갑옷: 붕대가 감긴 동안 −30% (' + (lost1 / lost0).toFixed(3) + ')'); });
T('mirrorarmor', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['mirrorarmor']); b.p.ward = 0; const e = b.en[0]; e.haze = 1; e.wrap = 3; const hp0 = e.hp; G0.hurtPlayer(b, 40, { src: e, single: 1, label: '시험' }); ok(e.hp < hp0 && e.haze === 1 && e.wrap === 3, '거울 갑옷: 때린 적에게 되돌린다, 허상 · 붕대는 지나간다 (' + (hp0 - e.hp).toFixed(1) + ')'); });
/* 열기 */
T('heatcut', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'warden', 13, ['coolplate']); b.heat = 90; let n = 0; for (let i = 0; i < 12; i++) { b.actN++; G0.fxRun(b.p, 'onAct', b, b.p, 'guard', {}, null); n++; } ok(b.heat === 70, '서늘한 흉갑: 장비로 내리는 열기는 전투마다 20까지 (' + b.heat + ')'); });
T('heatcut2', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'warden', 13, ['coolplate', 'wetrobe']); b.heat = 90; for (let i = 0; i < 8; i++) { G0.fxRun(b.p, 'onAct', b, b.p, 'guard', {}, null); G0.fxRun(b.p, 'onRound', b, b.p); } ok(b.heat === 70, '열기를 내리는 장비 둘이어도 합쳐 20까지 (' + b.heat + ')'); });
T('stormplate', () => { const mk = it => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'assassin', 13, it); b.p.ward = 0; b.heat = 100; b.heatWarn = b.round; const h0 = b.p.hp; G0.heatStorm(b); return [h0 - b.p.hp, b.p.ward]; }; const [l1, w1] = mk(['stormplate']); const [l0] = mk([]); ok(l1 < l0 * 0.8 + 0.01, '열풍 막이 판금: 열풍 피해 −30%에 보호막 +10 (' + l1.toFixed(1) + ' / ' + l0.toFixed(1) + ', 남은 보호막 ' + w1 + ')'); });
T('windwrap', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0]], mods: ['noon'] }, 'assassin', 13, ['windwrap']); b.heat = 100; b.heatWarn = b.round; b.actN = 3; G0.heatStorm(b); b.actN = 4; const d = hit(b, b.en[1], 100); const b2 = battle({ en: [['bruiser', 0], ['bruiser', 0]], mods: ['noon'] }, 'assassin', 13, []); b2.heat = 100; b2.heatWarn = b2.round; b2.actN = 3; G0.heatStorm(b2); b2.actN = 4; const d2 = hit(b2, b2.en[1], 100); ok(near(d / d2, 1.2, 0.02), '열풍 감는 손: 열풍이 분 뒤 +20% (' + (d / d2).toFixed(3) + ')'); });
T('stormbreaker', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'warden', 13, ['stormbreaker']); b.heat = 99; b.heatWarn = b.round || 0; const d = hit(b, b.en[0], 100); b.heat = 50; const b2 = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'warden', 13, []); const d2 = hit(b2, b2.en[0], 100); ok(near(d / d2, 1.2, 0.02), '열풍 가르는 도끼: 열풍이 예고된 동안 +20% (' + (d / d2).toFixed(3) + ')'); const h = b.heat; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.heat === h + 2, '열풍 가르는 도끼: 대가로 열기 +2'); });
T('sunbind', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['noon'] }, 'assassin', 13, ['sunbind']); b.heat = 45; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.en.every(e => G0.st(e, 'ignite') === 1) && b.heat === 48, '해 묶는 목걸이: 열기 40 이상이면 적 모두 화상 1, 열기 +3 (' + b.heat + ')'); });
T('noon-ring', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'assassin', 13, ['noonring']); b.p.st = 40; b.heat = 100; b.heatWarn = b.round; G0.heatStorm(b); ok(b.p.st >= 49, '한낮 반지: 열풍이 불면 스태미나 +10 (' + b.p.st + ')'); });
/* 화상 */
T('ashscale', () => { const mk = it => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, it); b.p.ward = 0; b.p.s.ignite = { stacks: 4, until: 9999, dur: 9999 }; const h0 = b.p.hp; G0.hurtPlayer(b, 10, { src: b.en[0], single: 1, label: '시험' }); return h0 - b.p.hp; }; const a = mk(['ashscale']), z = mk([]); ok(z - a > 0.9 && z - a < 1.1, '재 비늘 갑옷: 화상 추가 피해 4 → 3 (' + z.toFixed(2) + ' / ' + a.toFixed(2) + ')'); });
T('burntname', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['burntname']); const e = b.en[0]; G0.addS(b, e, 'ignite', 4); const d = hit(b, e, 10); ok(near(d, 10, 0.5), '불사른 이름의 검: 화상이 직접 피해에 더해지지 않는다 (' + d + ')'); const h0 = e.hp; G0.fxRun(b.p, 'onRound', b, b.p); ok(e.hp < h0 && G0.st(e, 'ignite') === 2, '불사른 이름의 검: 라운드가 끝나면 화상이 한 번 타오른다 (' + (h0 - e.hp).toFixed(1) + ', 화상 ' + G0.st(e, 'ignite') + ')'); });
T('ashpact', () => { const b = battle({ en: [['bruiser', 1]] }, 'assassin', 13, ['ashpact']); const e = b.en[0]; e.fire = 1; b.p.ward = 0; G0.fireCarry(b, e, 0, true); ok(G0.st(e, 'ignite') >= 1 && G0.st(b.p, 'ignite') >= 1, '재의 서약 반지: 나를 불붙인 적에게 화상을 돌려준다 (' + G0.st(e, 'ignite') + ')'); });
T('emberfeeder', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['emberfeeder']); b.p.s.ignite = { stacks: 2, until: 9999, dur: 9999 }; b.actN = 3; G0.fxRun(b.p, 'onRound', b, b.p); ok(G0.st(b.p, 'ignite') === 1, '불씨 먹는 검: 화상을 하나 먹는다'); b.actN = 4; const d = hit(b, b.en[0], 100); const b2 = battle({ en: [['bruiser', 0]] }, 'assassin', 13, []); const d2 = hit(b2, b2.en[0], 100); ok(near(d / d2, 1.12, 0.02), '불씨 먹는 검: 다음 공격 +12% (' + (d / d2).toFixed(3) + ')'); });
T('sunscorch', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['sunscorch']); const e = b.en[0]; G0.addS(b, e, 'ignite', 6); const h0 = e.hp; const d = hit(b, e, 10); ok(d > 10 + 20 && !G0.st(e, 'ignite'), '정오의 칼날: 화상 6을 한꺼번에 태운다 (' + d.toFixed(1) + ')'); });
T('pyrerobe', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]] }, 'assassin', 13, ['pyrerobe']); b.p.s.ignite = { stacks: 3, until: 9999, dur: 9999 }; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.en.every(e => G0.st(e, 'ignite') === 1), '분신의 법의: 화상 3 이상이면 적 모두 화상 1'); });
T('ashskin', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['ashskin']); b.p.ward = 0; b.p.s.ignite = { stacks: 4, until: 9999, dur: 9999 }; const h0 = b.p.hp; G0.hurtPlayer(b, 10, { src: b.en[0], single: 1, label: '시험' }); ok(near(h0 - b.p.hp, 10 * 0.5 * 0 + (h0 - b.p.hp), 99) && h0 - b.p.hp < 10.01, '재가 된 살갗: 화상이 추가 피해를 주지 않는다 (' + (h0 - b.p.hp).toFixed(2) + ')'); const d = hit(b, b.en[0], 100); const b2 = battle({ en: [['bruiser', 0]] }, 'assassin', 13, []); const d2 = hit(b2, b2.en[0], 100); ok(d / d2 > 1.11, '재가 된 살갗: 화상 한 칸마다 주는 피해 +4% (' + (d / d2).toFixed(3) + ')'); });
T('shieldknuckle', () => { const b = battle({ en: [['bruiser', 1]] }, 'warden', 13, ['shieldknuckle']); b.p.ward = 10; G0.addS(b, b.p, 'ignite', 2); ok(!G0.st(b.p, 'ignite'), '막 주먹: 보호막이 있는 동안 화상이 걸리지 않는다'); b.p.ward = 0; G0.addS(b, b.p, 'ignite', 2); ok(G0.st(b.p, 'ignite') === 2, '막 주먹: 보호막이 없으면 걸린다'); });
T('snuffgloves', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['snuffgloves']); const e = b.en[0]; e.fireNext = 2; hit(b, e, 10); ok(!e.fireNext, '불씨 끄는 장갑: 받은 불씨가 꺼진다'); });
/* 잠복 · 모래폭풍 */
T('surgesabre', () => { const b = battle({ en: [['lurker', 0], ['bruiser', 0]] }, 'assassin', 13, ['surgesabre']); const e = b.en[0]; G0.fxRun(b.p, 'onParry', b, b.p, e); ok(G0.st(e, 'vuln') === 2, '솟구침 받아치는 곡도: 흘린 잠복자에게 취약 2'); G0.fxRun(b.p, 'onEvade', b, b.p, b.en[1]); ok(!G0.st(b.en[1], 'vuln'), '잠복자가 아니면 걸리지 않는다'); });
T('surfacespear', () => { const mk = it => { const b = battle({ en: [['lurker', 0]] }, 'assassin', 13, it); const e = b.en[0]; e.under = 0; G0.addS(b, e, 'vuln', 2); return hit(b, e, 100); }; const r = mk(['surfacespear']) / mk([]); ok(near(r, 1.2, 0.01), '드러난 자의 창: 드러난 잠복자에게 +20% (' + r.toFixed(3) + ')'); });
T('duststaff', () => { const mk = it => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['sandstorm'] }, 'assassin', 13, it); return hit(b, b.en[1], 100); }; const r = mk(['duststaff']) / mk([]); ok(near(r, 1.15, 0.01), '먼지 바람 지팡이: 모래폭풍 방 후열 +15% (' + r.toFixed(3) + ')'); });
T('dunemail', () => { const b = battle({ en: [['lurker', 0]] }, 'warden', 13, ['dunemail']); b.p.ward = 0; G0.fxRun(b.p, 'onParry', b, b.p, b.en[0]); ok(b.p.ward > 0, '모래 갑주: 솟구침을 흘리면 보호막'); });
/* 일반 */
T('doublebrand', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['doublebrand']); const e = b.en[0]; b.cur = { id: 'basic' }; G0.addS(b, e, 'bleed', 1); b.cur = null; ok(G0.st(e, 'bleed') === 2, '겹낙인: 내가 거는 출혈이 1 더 걸린다 (' + G0.st(e, 'bleed') + ')'); G0.addS(b, b.p, 'weak', 1); ok(G0.st(b.p, 'weak') === 2, '겹낙인: 내게 걸리는 약화도 1 더 (' + G0.st(b.p, 'weak') + ')'); });
T('phoenixring', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]] }, 'warden', 13, ['phoenixring']); b.p.ward = 0; b.p.hp = 5; G0.hurtPlayer(b, 999, { src: b.en[0], single: 1, label: '시험' }); ok(b.p.hp > b.p.hpMax * 0.4 && !b.over && b.en.every(e => G0.st(e, 'ignite') >= 4), '재에서 일어나는 반지: 쓰러질 때 생명력 절반으로 일어난다 (' + Math.round(b.p.hp) + ')'); b.p.hp = 5; G0.hurtPlayer(b, 999, { src: b.en[0], single: 1, label: '시험' }); ok(b.over === 'lose' || b.p.hp <= 0, '재에서 일어나는 반지: 한 런에 한 번뿐'); });
T('afterglow', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0], ['archer', 0]] }, 'assassin', 13, ['afterglow']); const e = b.en[0]; G0.addS(b, e, 'ignite', 4); G0.addS(b, e, 'bleed', 3); e.hp = 1; hit(b, e, 50); ok(!e.alive && b.en.slice(1).every(x => G0.st(x, 'ignite') === 2 && G0.st(x, 'bleed') === 2), '잔광의 목걸이: 쓰러진 적의 상태 절반이 남은 적에게 번진다 (' + G0.st(b.en[1], 'ignite') + ',' + G0.st(b.en[1], 'bleed') + ')'); });
T('firstlight', () => { const mk = it => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, it); const e = b.en[0]; const d1 = hit(b, e, 50); const d2 = hit(b, e, 50); return [d1, d2]; }; const [a1, a2] = mk(['firstlight']); const [z1, z2] = mk([]); ok(near(a1 / z1, 1.3, 0.02) && near(a2 / z2, 0.98, 0.02), '첫 빛의 목걸이: 첫 피해 +30%, 그 뒤 −2% (' + (a1 / z1).toFixed(3) + ', ' + (a2 / z2).toFixed(3) + ')'); });
T('cullingaxe', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['cullingaxe']); const e = b.en[0]; const d1 = hit(b, e, 10); e.hp = e.hpMax * 0.1; const d2 = hit(b, e, 10); ok(near(d1, 9, 0.2) && near(d2, 13, 0.2), '솎아 베는 도끼: 가득 찬 적 −10%, 20% 이하 +30% (' + d1 + ', ' + d2 + ')'); });
T('triplering', () => { const mk = it => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, it); const e = b.en[0]; G0.addPoison(b, e, 2, 1); G0.addS(b, e, 'bleed', 2); G0.addS(b, e, 'ignite', 1); e.s.ignite = { stacks: 0, until: 9999, dur: 9999 }; delete e.s.ignite; G0.addS(b, e, 'ignite', 1); const d = hit(b, e, 100); return d; }; ok(mk(['triplering']) > 0, '세 겹 반지 실행'); });
T('eyeofnoon', () => { const mk = it => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, it); b.en[0].intent = { k: 'heavy' }; return hit(b, b.en[0], 100); }; const r = mk(['eyeofnoon']) / mk([]); ok(near(r, 1.2, 0.02), '정오의 눈: 큰 공격이 예고되면 +20% (' + r.toFixed(3) + ')'); });
T('soloring', () => { const mk = it => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, it); return hit(b, b.en[0], 100); }; const r = mk(['soloring']) / mk([]); ok(near(r, 1.1, 0.01), '마지막 한 명의 반지: 적이 하나면 +10% (' + r.toFixed(3) + ')'); });
T('oasis_gourd', () => { const b = battle({ en: [['bruiser', 0]] }, 'warden', 13, ['oasis_gourd']); b.p.flask.life = G0.flaskCap(b.p, 'life'); const c0 = b.p.flask.life; b.p.hp = b.p.hpMax * 0.5; G0.playerAct(b, 'flaskL', null); const c1 = b.p.flask.life; ok(c1 === c0, '오아시스 호리병: 첫 모금은 충전을 쓰지 않는다 (' + c0 + ' → ' + c1 + ')'); b.p.st = b.p.stMax; G0.playerAct(b, 'flaskL', null); ok(b.p.flask.life === c1 - 1 || b.over, '두 번째는 쓴다 (' + b.p.flask.life + ')'); });
T('hazebottle', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0]], mods: ['haze'] }, 'warden', 13, ['hazebottle']); G0.playerAct(b, 'flaskM', null); ok(b.en.every(e => !(e.haze > 0)), '신기루 병: 정화 플라스크가 허상을 모두 걷는다'); });
T('wardfont', () => { const b = battle({ en: [['bruiser', 0]] }, 'warden', 13, ['wardfont']); b.p.ward = 0; G0.playerAct(b, 'flaskM', null); ok(b.p.ward >= G0.wardMax(b.p) * 0.45, '보호막 샘: 정화 플라스크가 보호막을 절반까지 채운다 (' + Math.round(b.p.ward) + '/' + G0.wardMax(b.p) + ')'); });
T('scapeflask', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]] }, 'warden', 13, ['scapeflask']); G0.addS(b, b.p, 'ignite', 4); G0.playerAct(b, 'flaskM', null); ok(!G0.st(b.p, 'ignite') && b.en.every(e => G0.st(e, 'ignite') >= 2), '속죄양 병: 내 화상을 적에게 절반씩 나눠 건다'); });
T('mirrorshock', () => { const b = battle({ en: [['bruiser', 0]] }, 'elementalist', 13, ['mirrorshock']); const e = b.en[0]; e.haze = 1; G0.fxRun(b.p, 'onShock', b, b.p, e); ok(e.haze === 0, '거울 충격 반지: 열충격이 허상을 한 겹 걷는다'); const k0 = e.brk; G0.fxRun(b.p, 'onShock', b, b.p, e); ok(e.brk > k0, '허상이 없으면 붕괴 +4'); });
T('stormbeads', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['sandstorm'] }, 'warden', 13, ['stormbeads']); b.p.ward = 0; const e = b.en[0]; e.hp = 1; hit(b, e, 50); ok(b.p.ward >= 10, '폭풍 묵주: 전열이 모두 쓰러지면 보호막 +10 (' + b.p.ward + ')'); });
T('kilnring', () => { const mk = it => { const b = battle({ en: [['bruiser', 0]], mods: ['brazier'] }, 'assassin', 13, it); G0.addS(b, b.en[0], 'ignite', 4); return hit(b, b.en[0], 10); }; const a = mk(['kilnring']), z = mk([]); ok(near((a - 10) / (z - 10), 1.2, 0.02), '가마 반지: 불씨 화로 방에서 화상 추가 피해 +20% (' + z.toFixed(2) + ' → ' + a.toFixed(2) + ')'); });
/* 둘째 묶음: 갑옷 · 장갑 · 반지 · 목걸이 · 플라스크 */
const loss = (b, raw, o) => { const h0 = b.p.hp; G0.hurtPlayer(b, raw, Object.assign({ src: b.en[0], single: 1, label: '시험' }, o || {})); return h0 - b.p.hp; };
const withItems = (items, f) => { const b = battle({ en: [['bruiser', 0], ['archer', 0]] }, 'assassin', 13, items); b.p.ward = 0; return f(b); };
const ratio = (items, f) => withItems(items, f) / withItems([], f);
T('veilcloak', () => { const r = ratio(['veilcloak'], b => { b.en[0].haze = 1; return loss(b, 30); }); ok(near(r, 0.92, 0.01), '엷은 베일 외투: 허상 두른 적에게 −8% (' + r.toFixed(3) + ')'); });
T('wrapvest', () => { const r = ratio(['wrapvest'], b => { b.en[0].wrap = 3; return loss(b, 30); }); ok(near(r, 0.92, 0.01), '붕대 덧댄 조끼 −8% (' + r.toFixed(3) + ')'); });
T('sandcoat', () => { const r = ratio(['sandcoat'], b => { const e = b.en[1]; return loss(b, 30, { src: e }); }); ok(near(r, 1, 0.001), '모래 먼지 외투: 모래폭풍이 아니면 그대로'); const mk = it => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['sandstorm'] }, 'assassin', 13, it); b.p.ward = 0; return loss(b, 30, { src: b.en[1] }); }; ok(near(mk(['sandcoat']) / mk([]), 0.85, 0.01), '모래 먼지 외투: 모래폭풍 방 후열 −15%'); });
T('lurkboots', () => { const r = ratio(['lurkboots'], b => loss(b, 30, { src: Object.assign(b.en[0], { role: 'lurker' }), charged: 1 })); ok(near(r, 0.9, 0.01), '모래 다지는 장화 갑옷: 솟구침 −10% (' + r.toFixed(3) + ')'); });
T('sunshade', () => { const r = ratio(['sunshade'], b => loss(b, 30, { label: '열풍', aoe: 1, spell: 1, charged: 1 })); ok(near(r, 0.85, 0.01), '차양 갑옷: 열풍 −15% (' + r.toFixed(3) + ')'); });
T('embercloak', () => { const r = ratio(['embercloak'], b => { b.en[0].fire = 1; return loss(b, 30); }); ok(near(r, 0.92, 0.01), '불씨 가죽옷 −8% (' + r.toFixed(3) + ')'); });
T('burnedmail', () => { const b = battle({ en: [['bruiser', 0]] }, 'warden', 13, ['burnedmail']); G0.addS(b, b.p, 'ignite', 3); ok(G0.st(b.p, 'ignite') === 2, '그슬린 사슬갑: 화상 −1 (' + G0.st(b.p, 'ignite') + ')'); const b2 = battle({ en: [['bruiser', 0]] }, 'warden', 13, ['burnedmail']); G0.addS(b2, b2.p, 'ignite', 1); ok(G0.st(b2.p, 'ignite') === 1, '최소 1'); });
T('scorpionamulet', () => { const b = battle({ en: [['bruiser', 0]] }, 'warden', 13, ['scorpionamulet']); G0.addS(b, b.p, 'bleed', 2); ok(G0.st(b.p, 'bleed') === 1, '전갈 부적: 출혈 −1'); });
T('emberguard', () => { const b = battle({ en: [['ember', 0], ['bruiser', 0]] }, 'assassin', 13, ['emberguard']); b.p.ward = 0; G0.addS(b, b.p, 'ignite', 4); const e = b.en[0]; e.hp = 1; hit(b, e, 50); ok(G0.st(b.p, 'ignite') === 2, '불씨 막이 판갑: 투척병이 쓰러지면 화상 −2 (' + G0.st(b.p, 'ignite') + ')'); const r = ratio(['emberguard'], b => loss(b, 30, { src: Object.assign(b.en[0], { role: 'ember' }) })); ok(near(r, 0.8, 0.01), '투척병의 공격 −20%'); });
T('unwraplink', () => { const b = battle({ en: [['wrapped', 0]] }, 'warden', 13, ['unwraplink']); b.actN = 1; b.p.ward = 0; G0.addS(b, b.en[0], 'ignite', 1); ok(b.p.ward > 0, '붕대 푸는 자의 겉옷: 붕대를 벗기면 보호막 (' + b.p.ward + ')'); });
T('hazewalker', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['hazewalker']); const e = b.en[0]; e.haze = 1; hit(b, e, 10); ok(G0.st(b.p, 'protect') === 1, '아지랑이 걷는 자의 옷: 허상을 걷으면 보호 1'); b.p.ward = 0; const r = ratio(['hazewalker'], b => loss(b, 30)); ok(near(r, 1.05, 0.01), '허상 없는 적에게 받는 피해 +5% (' + r.toFixed(3) + ')'); });
T('wrapbreakermail', () => { const b = battle({ en: [['wrapped', 0]] }, 'warden', 13, ['wrapbreakermail']); b.p.ward = 0; const e = b.en[0]; loss(b, 20, { src: e }); ok(e.wrap === 2, '붕대 찢는 갑주: 붕대 감긴 적이 치면 붕대가 한 번 닳는다 (' + e.wrap + ')'); });
T('sandmantle', () => { const b = battle({ en: [['lurker', 0], ['bruiser', 0]] }, 'warden', 13, ['sandmantle']); b.en[0].under = 1; b.p.ward = 0; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.p.ward > 0, '모래 외투: 숨은 적이 있는 라운드 끝 보호막 (' + b.p.ward + ')'); });
T('ashplate', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['ashplate']); b.p.ward = 0; b.p.s.ignite = { stacks: 5, until: 9999, dur: 9999 }; const l1 = loss(b, 10); const b2 = battle({ en: [['bruiser', 0]] }, 'assassin', 13, []); b2.p.ward = 0; b2.p.s.ignite = { stacks: 5, until: 9999, dur: 9999 }; const l0 = loss(b2, 10); ok(l1 > 0 && l1 < l0 * 1.2, '재 흡수 흉갑: 화상이 있으면 받는 피해 감소, 화상 추가 피해 +15% (' + l1.toFixed(2) + ' / ' + l0.toFixed(2) + ')'); });
T('emberbulwark', () => { const b = battle({ en: [['bruiser', 0]] }, 'warden', 13, ['emberbulwark']); b.p.ward = 5; b.p.s.ignite = { stacks: 4, until: 9999, dur: 9999 }; const x = G0.kwTaken(b, b.p, 10, { single: 1 }); ok(near(x, 12, 0.01), '불씨 보루 판갑: 보호막이 있으면 화상 추가 피해 절반 (' + x + ')'); });
T('bloodmail', () => { const b = battle({ en: [['bruiser', 0]] }, 'bloodmage', 13, ['bloodmail']); b.p.ward = 0; G0.fxRun(b.p, 'onSkill', b, b.p, { id: 'x', s: { fx: [{ k: 'hpCost', pct: 0.05 }] } }); ok(b.p.ward > 0, '피의 대가 갑옷: 생명력 비용 → 보호막 (' + b.p.ward + ')'); });
T('sandveil', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['sandstorm'] }, 'warden', 13, ['sandveil']); b.p.st = 10; b.en[1].hp = 1; hit(b, b.en[1], 50); ok(b.p.st >= 20, '모래막 베일 갑옷: 후열을 쓰러뜨리면 스태미나 +10 (' + b.p.st + ')'); });
T('stormcloak', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['sandstorm'] }, 'warden', 13, ['stormcloak']); b.p.ward = 0; b.en[0].hp = 1; hit(b, b.en[0], 50); ok(b.p.ward > 0, '폭풍 헤치는 망토: 전열을 쓰러뜨리면 보호막'); });
T('evadecoat', () => { const b = battle({ en: [['bruiser', 0]] }, 'hunter', 13, ['evadecoat']); b.p.ward = 0; b.p.s.ignite = { stacks: 2, until: 9999, dur: 9999 }; G0.fxRun(b.p, 'onEvade', b, b.p, b.en[0]); ok(b.p.ward > 0 && G0.st(b.p, 'ignite') === 1, '신기루 회피복: 피하면 보호막 +4, 화상 −1'); });
T('stancehabit', () => { const b = battle({ en: [['bruiser', 0]] }, 'monk', 13, ['stancehabit']); b.p.ward = 0; b.p.s.ignite = { stacks: 5, until: 9999, dur: 9999 }; b.p.stance = { id: 'x' }; const x = G0.kwTaken(b, b.p, 10, { single: 1 }); ok(near(x, 13, 0.01), '불 삼킨 도복: 자세 중 화상 추가 피해 −40% (' + x + ')'); });
T('ashpenance', () => { const b = battle({ en: [['bruiser', 0]] }, 'confessor', 13, ['ashpenance']); b.p.s.ignite = { stacks: 3, until: 9999, dur: 9999 }; b.p.s.weak = { stacks: 1, until: 9999, dur: 9999 }; G0.fxRun(b.p, 'onRound', b, b.p); ok(G0.st(b.p, 'ignite') === 2, '재 참회복: 해로운 상태가 둘 이상이면 화상 1 지움'); });
T('coolgloves', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'assassin', 13, ['coolgloves']); b.heat = 50; G0.fxRun(b.p, 'onSkill', b, b.p, { id: 'x', s: { fx: [] } }); ok(b.heat === 49, '젖은 장갑: 스킬 → 열기 −1'); });
T('burnmitt', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['burnmitt']); b.p.st = 30; G0.addS(b, b.p, 'ignite', 1); ok(b.p.st === 34, '화상 감싸는 장갑: 스태미나 +4 (' + b.p.st + ')'); G0.addS(b, b.p, 'ignite', 1); ok(b.p.st === 34, '라운드마다 한 번'); });
T('kindlewraps', () => { const b = battle({ en: [['wrapped', 0]] }, 'assassin', 13, ['kindlewraps']); const e = b.en[0]; G0.addS(b, e, 'ignite', 1); ok(G0.st(e, 'ignite') === 3, '불붙은 붕대 장갑: 붕대가 타면 화상 +2 (' + G0.st(e, 'ignite') + ')'); });
T('stainedglove', () => { const b = battle({ en: [['wrapped', 0]] }, 'assassin', 13, ['stainedglove']); const e = b.en[0]; b.actN++; b.cur = { id: 'x', skill: 1, s: { fx: [{ k: 'poison', n: 3 }] } }; G0.hurtEnemy(b, e, 5, { single: 1, melee: 1 }); b.cur = null; ok(G0.st(e, 'poison') === 1, '얼룩 장갑: 붕대 감긴 적에게 중독 스킬 +1 (' + G0.st(e, 'poison') + ')'); });
T('splitglove', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0]] }, 'assassin', 13, ['splitglove']); b.en[0].haze = 1; const k0 = b.en[1].brk; hit(b, b.en[0], 10); ok(b.en[1].brk >= k0 + 8, '갈라진 장갑: 허상을 걷으면 다른 적 붕괴 +10, 대가로 허상 없는 적에게 기본 공격 붕괴 −2 (' + (b.en[1].brk - k0) + ')'); });
T('quickdraw', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0]] }, 'assassin', 13, ['quickdraw']); b.en[0].haze = 1; b.en[0].hp = 1; b.en[0].alive; G0.fxRun(b.p, 'onKill', b, b.p, b.en[0]); ok(b.p.fxQuickNext === 1, '속사 장갑: 허상을 두른 적이 쓰러지면 빠른 칸'); });
T('unveilfist', () => { const b = battle({ en: [['bruiser', 0], ['wrapped', 0]] }, 'assassin', 13, ['unveilfist']); b.en[0].haze = 1; b.en[1].wrap = 3; hit(b, b.en[0], 10); G0.addS(b, b.en[1], 'ignite', 1); const d = hit(b, b.en[0], 100); const bb = battle({ en: [['bruiser', 0], ['wrapped', 0]] }, 'assassin', 13, []); const d0 = hit(bb, bb.en[0], 100); ok(near(d / d0, 1.45, 0.06), '장막 부수는 주먹: 허상 · 붕대를 벗기면 쌓여 다음 공격 +50% (−5%) (' + (d / d0).toFixed(3) + ')'); });
T('kindlerglove', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['kindlerglove']); const e = b.en[0]; b.actN++; b.cur = { id: 'x', skill: 1, s: { fx: [{ k: 'st', s: 'ignite', n: 2 }] } }; G0.hurtEnemy(b, e, 5, { single: 1, melee: 1 }); b.cur = null; ok(G0.st(e, 'ignite') === 2, '불쏘시개 장갑: 화상 없는 적에게 +2 (' + G0.st(e, 'ignite') + ')'); });
T('furnacegauntlet', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'assassin', 13, ['furnacegauntlet']); b.heat = 30; b.p.st = 20; G0.fxRun(b.p, 'onRound', b, b.p); const h1 = b.heat; b.heat += 10; b.p.st = 20; G0.fxRun(b.p, 'onRound', b, b.p); ok(h1 === 34 && b.p.st >= 29, '용광로 건틀릿: 오른 만큼 스태미나, 대가로 열기 +4 (' + b.p.st + ', ' + b.heat + ')'); });
T('heatpalm', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'assassin', 13, ['heatpalm']); b.heat = 60; const e = b.en[0]; b.actN++; b.cur = { id: 'basic', time: 0.5 }; const k0 = e.brk; G0.addBreak(b, e, 5); b.cur = null; ok(e.brk - k0 >= 5 + 6 - 0.01, '달군 손바닥: 열기 60이면 빠른 행동 붕괴 +6 (' + (e.brk - k0).toFixed(1) + ')'); });
T('lowtide-sandtimer', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['lowtide']); b.p.ward = 0; b.p.hp = b.p.hpMax * 0.4; const l1 = loss(b, 20); const b2 = battle({ en: [['bruiser', 0]] }, 'assassin', 13, []); b2.p.ward = 0; b2.p.hp = b2.p.hpMax * 0.4; const l0 = loss(b2, 20); ok(near(l1 / l0, 0.75, 0.02), '썰물 반지: 절반 아래에서 첫 피해 −25% (' + (l1 / l0).toFixed(3) + ')'); const l2 = loss(b, 20); ok(near(l2 / l0, 1, 0.02), '라운드마다 한 번'); });
T('ashgrief', () => { const b = battle({ en: [['bruiser', 0]] }, 'bloodmage', 13, ['ashgrief']); b.p.s.ignite = { stacks: 2, until: 9999, dur: 9999 }; G0.fxRun(b.p, 'onSkill', b, b.p, { id: 'x', s: { fx: [{ k: 'hpCost', pct: 0.05 }] } }); ok(G0.st(b.p, 'ignite') === 1, '재의 애도 목걸이: 생명력 비용 → 화상 −1'); });
T('rimeheart', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['rimeheart']); const e = b.en[0]; e.haze = 1; G0.addS(b, e, 'chill', 1); G0.fxRun(b.p, 'onRound', b, b.p); ok(!e.haze, '서리 심장: 둔화된 적의 허상이 걷힌다'); });
T('clearsight', () => { const mk = it => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0]] }, 'assassin', 13, it); b.en[0].haze = 1; return hit(b, b.en[1], 100); }; ok(near(mk(['clearsight']) / mk([]), 1.15, 0.01), '맑은 눈 목걸이: 허상 없는 적에게 +15%'); });
T('vitalwrap', () => { const b = battle({ en: [['wrapped', 0]] }, 'assassin', 13, ['vitalwrap']); b.p.hp = b.p.hpMax * 0.5; const h0 = b.p.hp; G0.fxRun(b.p, 'onKill', b, b.p, b.en[0]); ok(b.p.hp > h0, '생명의 붕대 목걸이: 붕대 감긴 채 쓰러지면 생명력 회복'); });
T('wrapknot', () => { const b = battle({ en: [['wrapped', 0]] }, 'assassin', 13, ['wrapknot']); const e = b.en[0]; G0.addS(b, e, 'bleed', 2); G0.addS(b, e, 'ignite', 1); ok(G0.st(e, 'bleed') === 3, '붕대 매듭 부적: 붕대가 풀리면 걸린 상태가 1씩 오른다 (' + G0.st(e, 'bleed') + ')'); });
T('pyrewrap', () => { const b = battle({ en: [['wrapped', 0], ['bruiser', 0]] }, 'assassin', 13, ['pyrewrap']); G0.addS(b, b.en[0], 'ignite', 1); ok(G0.st(b.en[1], 'ignite') === 2, '붕대 사르는 목걸이: 다른 적 모두 화상 2'); });
T('coolheart', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'warden', 13, ['coolheart']); b.p.ward = 0; b.heat = 30; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.p.ward > 0, '식은 심장: 열기 50 아래 → 보호막'); b.p.ward = 0; b.heat = 60; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.p.ward === 0, '50 이상이면 없다'); });
T('patience', () => { const b = battle({ en: [['lurker', 0]] }, 'assassin', 13, ['patience']); b.en[0].under = 1; b.p.st = 10; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.p.st === 18, '기다리는 자의 목걸이: 숨은 적 → 스태미나 +8'); G0.fxRun(b.p, 'onParry', b, b.p, b.en[0]); ok(G0.st(b.p, 'haste') === 1, '솟구침을 흘리면 가속 1'); });
T('shadowcharm', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]] }, 'assassin', 13, ['shadowcharm']); G0.fxRun(b.p, 'onParry', b, b.p, b.en[0]); ok(b.en.every(e => G0.st(e, 'poison') === 1), '그림자 부적: 흘리면 적 모두 중독 1'); });
T('sunbind-heat', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'assassin', 13, ['heatamulet']); b.heat = 85; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.heat === 79, '서늘한 구슬: 열기 80 이상 → −6'); });
T('transferamulet', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'confessor', 13, ['transferamulet']); b.heat = 50; G0.fxRun(b.p, 'onSkill', b, b.p, { id: 'x', s: { fx: [{ k: 'transfer' }] } }); ok(b.heat === 48, '전가의 목걸이: 옮기면 열기 −2'); });
T('afterglow-poison', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]] }, 'assassin', 13, ['afterglow']); G0.addPoison(b, b.en[0], 6, 1); b.en[0].hp = 1; hit(b, b.en[0], 50); ok(G0.st(b.en[1], 'poison') === 3, '잔광의 목걸이: 중독도 절반 (' + G0.st(b.en[1], 'poison') + ')'); });
/* 플라스크 */
const flask = (items, id, setup, room) => { const b = battle(room || { en: [['bruiser', 0], ['wrapped', 0]] }, 'warden', 13, items); b.p.ward = 0; b.p.hp = b.p.hpMax * 0.5; b.p.flask = { life: 3, mana: 3, stam: 3 }; if (setup) setup(b); G0.playerAct(b, id, null); return b; };
T('hazewater', () => { const b = flask(['hazewater'], 'flaskM', b => { b.en[0].haze = 2; }); ok(b.en[0].haze === 1, '투명한 물병: 정화 플라스크 → 허상 한 겹 (' + b.en[0].haze + ')'); });
T('wrapwater', () => { const b = flask(['wrapwater'], 'flaskL', null); ok(b.en[1].wrap === 2 || b.en[1].wrap === 3 && false, '기름 먹은 물병: 붕대가 한 번 닳는다 (' + b.en[1].wrap + ')'); });
T('coolwater', () => { const b = flask(['coolwater'], 'flaskS', b => { b.heat = 50; }, { en: [['bruiser', 0]], mods: ['noon'] }); ok(b.heat <= 50 - 8 + 10, '찬 샘물: 스태미나 플라스크 → 열기 −8'); });
T('sapflask', () => { const b = flask(['sapflask'], 'flaskL', b => { b.p.s.ignite = { stacks: 3, until: 9999, dur: 9999 }; }); ok(!G0.st(b.p, 'ignite'), '수액 플라스크: 화상이 모두 꺼진다'); });
T('emberbottle', () => { const b = flask(['emberbottle'], 'flaskM', b => { b.p.s.ignite = { stacks: 3, until: 9999, dur: 9999 }; }); ok(G0.st(b.p, 'ignite') <= 2 && b.p.ward > 0, '불씨 담은 병: 화상 1 지우고 보호막 (' + G0.st(b.p, 'ignite') + ', ' + b.p.ward + ')'); });
T('dustwater', () => { const b = flask(['dustwater'], 'flaskL', null, { en: [['bruiser', 0]], mods: ['sandstorm'] }); const b0 = flask([], 'flaskL', null, { en: [['bruiser', 0]], mods: ['sandstorm'] }); ok(b.p.hp > b0.p.hp, '모래 거른 물: 모래폭풍 방에서 생명력 5% 더'); });
T('tollwater', () => { const b = battle({ en: [['bruiser', 0]] }, 'warden', 13, ['tollwater']); b.p.st = 10; G0.fxRun(b.p, 'onFlask', b, b.p, 'life'); ok(G0.st(b.p, 'bleed') === 1 && b.p.st === 20, '통행료 물병: 스태미나 +10, 출혈 1 (' + b.p.st + ')'); });
T('windwater', () => { const b = flask(['windwater'], 'flaskS', b => { b.p.st = 10; }); ok(G0.st(b.p, 'haste') >= 1, '바람 물병: 가속 1'); });
T('mirrorflask', () => { const b = flask(['mirrorflask'], 'flaskM', b => { b.en[0].haze = 1; b.en[1].haze = 1; }); ok(b.en.every(e => !e.haze) && b.p.ward >= 6, '거울 물병: 허상 모두 걷고 하나마다 보호막 +3 (' + b.p.ward + ')'); });
T('oilflask', () => { const b = flask(['oilflask'], 'flaskL', null); ok(!b.en[1].wrap, '기름 플라스크: 붕대 감긴 적에게 화상 → 붕대가 탄다'); });
T('stormflask', () => { const b = flask(['stormflask'], 'flaskL', null, { en: [['bruiser', 0], ['archer', 0]], mods: ['sandstorm'] }); ok(b.en[1].brk > 0, '폭풍 병: 후열 적 붕괴 (' + b.en[1].brk + ')'); });
T('chillflask', () => { const b = flask(['chillflask'], 'flaskL', b => { b.heat = 60; }, { en: [['bruiser', 0]], mods: ['noon'] }); ok(b.heat <= 60 - 10 + 10, '서늘한 병: 열기 −10'); });
T('soakedflask', () => { const b = flask(['soakedflask'], 'flaskL', null); b.p.ward = 0; const h0 = b.p.hp; G0.hurtPlayer(b, 40, { label: '열풍', aoe: 1, spell: 1, charged: 1 }); const b2 = flask([], 'flaskL', null); b2.p.ward = 0; const g0 = b2.p.hp; G0.hurtPlayer(b2, 40, { label: '열풍', aoe: 1, spell: 1, charged: 1 }); ok((h0 - b.p.hp) < (g0 - b2.p.hp) * 0.6, '적신 천 병: 마신 라운드 열풍 절반'); });
T('wrapsolvent', () => { const b = flask(['wrapsolvent'], 'flaskM', null); ok(b.en[1].wrap === 2, '붕대 녹이는 병: 붕대가 한 번 닳는다 (' + b.en[1].wrap + ')'); });
T('gritwater', () => { const b = flask(['gritwater'], 'flaskL', null); b.p.s.ignite = { stacks: 4, until: 9999, dur: 9999 }; const x = G0.kwTaken(b, b.p, 10, { single: 1 }); ok(near(x, 12, 0.01), '오기 물병: 다음 라운드까지 화상 추가 피해 −50% (' + x + ')'); });
T('veinwater', () => { const b = flask(['veinwater'], 'flaskL', b => { G0.addS(b, b.en[0], 'bleed', 2); G0.addS(b, b.en[1], 'bleed', 2); b.p.st = 10; }); ok(b.p.st >= 20, '핏줄 물병: 출혈된 적 둘 → 스태미나 +10 (' + b.p.st + ')'); });
T('plaguewater', () => { const b = flask(['plaguewater'], 'flaskL', b => { G0.addPoison(b, b.en[0], 2, 1); }); ok(G0.st(b.en[0], 'poison') >= 4, '역병 물병: 중독 +2 (' + G0.st(b.en[0], 'poison') + ')'); });
T('furnacebottle', () => { const b = flask(['furnacebottle'], 'flaskS', b => { b.heat = 60; b.p.st = 10; }, { en: [['bruiser', 0]], mods: ['noon'] }); ok(b.p.st >= 25, '가마 병: 열기 60 → 스태미나 +15 (' + b.p.st + ')'); });
T('emberwell', () => { const b = flask(['emberwell'], 'flaskL', b => { b.p.s.ignite = { stacks: 3, until: 9999, dur: 9999 }; }); const b0 = flask([], 'flaskL', null); ok(!G0.st(b.p, 'ignite') && b.p.hp > 0, '불씨 우물: 화상을 모두 지운다'); });
T('sandsea', () => { const b = flask(['sandsea'], 'flaskL', null, { en: [['bruiser', 0], ['archer', 0]], mods: ['sandstorm'] }); ok(G0.st(b.en[1], 'chill') === 1, '모래 바다 병: 모래폭풍 방 후열 둔화 1'); });
T('kibreath', () => { const b = flask(['kibreath'], 'flaskS', b => { b.p.st = 10; }); ok(G0.st(b.p, 'empower') >= 2, '호흡 병: 기 +2'); });
T('purgingchalice', () => { const b = flask(['purgingchalice'], 'flaskM', b => { b.p.s.ignite = { stacks: 2, until: 9999, dur: 9999 }; b.p.s.weak = { stacks: 1, until: 9999, dur: 9999 }; }); ok(b.en.every(e => G0.st(e, 'weak') >= 2) && !G0.st(b.p, 'ignite'), '정화의 잔: 지운 종류마다 적 약화 (' + G0.st(b.en[0], 'weak') + ')'); });

/* 셋째 묶음: 남은 효과 */
const dmgRatio = (items, room, bd, prep, raw) => { const f = it => { const b = battle(room, bd || 'assassin', 13, it); const e = b.en[0]; if (prep) prep(b, e); return hit(b, e, raw || 100); }; return f(items) / f([]); };
T('ashrake', () => { const f = it => { const b = battle({ en: [['wrapped', 0]] }, 'assassin', 13, it); const e = b.en[0]; b.actN++; b.cur = { id: 'basic' }; const k0 = e.brk; G0.addBreak(b, e, 5); b.cur = null; return e.brk - k0; }; ok(f(['ashrake']) - f([]) >= 4 - 0.01, '재 긁는 갈퀴: 붕대 감긴 적에게 기본 공격 붕괴 +4'); });
T('brandaxe', () => { const r = dmgRatio(['brandaxe'], { en: [['bruiser', 1]] }, 'assassin', (b, e) => { e.fire = 1; }); ok(near(r, 1.08, 0.01), '낙인 깨는 도끼 +8% (' + r.toFixed(3) + ')'); });
T('noonblade', () => { const r = dmgRatio(['noonblade'], { en: [['bruiser', 0]], mods: ['noon'] }, 'assassin', (b) => { b.heat = 60; }); ok(near(r, 1.06, 0.01), '한낮의 검: 열기 50 이상 기본 공격 +6% (' + r.toFixed(3) + ')'); });
T('lurkspike', () => { const f = it => { const b = battle({ en: [['lurker', 0], ['bruiser', 0], ['archer', 0]] }, 'assassin', 13, it); b.en[0].under = 1; return hit(b, b.en[2], 100); }; ok(near(f(['lurkspike']) / f([]), 1.1, 0.01), '숨은 적 찌르개: 숨은 적이 있으면 후열 +10%'); });
T('driftbow', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]] }, 'hunter', 13, ['driftbow']); b.p.st = 10; hit(b, b.en[1], 10, { id: 'basic', ranged: 1 }, { single: 1 }); ok(b.p.st === 13, '모래 바람 활: 원거리로 후열을 맞히면 스태미나 +3 (' + b.p.st + ')'); });
T('priestbane', () => { const r = dmgRatio(['priestbane'], { en: [['healer', 0]] }); ok(near(r, 1.12, 0.01), '무녀 잡는 낫 +12%'); });
T('heatsabre', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'assassin', 13, ['heatsabre']); b.heat = 70; hit(b, b.en[0], 10); ok(G0.st(b.en[0], 'ignite') === 1, '달군 곡도: 열기 60 이상이면 근접 공격이 화상 1'); });
T('emberhunter', () => { const b = battle({ en: [['ember', 0], ['bruiser', 0]] }, 'warden', 13, ['emberhunter']); b.p.ward = 0; b.en[0].hp = 1; hit(b, b.en[0], 10); ok(b.p.ward >= 4 - 0.01, '투척병 사냥칼: 투척병을 쓰러뜨리면 보호막 +4 (' + b.p.ward + ')'); });
T('scorpionrod', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['scorpionrod']); G0.addS(b, b.en[0], 'bleed', 2); hit(b, b.en[0], 10); ok(G0.st(b.en[0], 'bleed') >= 3, '전갈 꼬리 채찍: 출혈 +1'); const b2 = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['scorpionrod']); G0.addPoison(b2, b2.en[0], 2, 1); hit(b2, b2.en[0], 10); ok(G0.st(b2.en[0], 'poison') === 3, '중독이면 중독 +1'); });
T('echoblade', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0]] }, 'assassin', 13, ['echoblade']); b.en[0].haze = 1; hit(b, b.en[0], 10); const k0 = b.en[1].brk; b.actN++; b.cur = { id: 'basic' }; G0.addBreak(b, b.en[1], 5); b.cur = null; ok(b.en[1].brk - k0 >= 17 - 0.01, '메아리 칼: 허상을 걷으면 다음 행동 붕괴 +12 (' + (b.en[1].brk - k0) + ')'); });
T('cinderchain', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['cinderchain']); b.p.s.ignite = { stacks: 2, until: 9999, dur: 9999 }; hit(b, b.en[0], 10); ok(G0.st(b.p, 'ignite') === 1 && G0.st(b.en[0], 'ignite') >= 1, '재 옮기는 사슬: 내 화상 1을 대상에게'); });
T('dunescythe', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['sandstorm'] }, 'assassin', 13, ['dunescythe']); const k0 = b.en[1].brk; b.en[0].hp = 1; hit(b, b.en[0], 50); ok(b.en[1].brk - k0 >= 12 - 0.01, '모래 언덕의 낫: 전열을 쓰러뜨리면 후열 붕괴 +12 (' + (b.en[1].brk - k0) + ')'); });
T('pactblade', () => { const b = battle({ en: [['bruiser', 0]] }, 'bloodmage', 13, ['pactblade']); b.actN = 1; G0.fxRun(b.p, 'onSkill', b, b.p, { id: 'x', s: { fx: [{ k: 'hpCost', pct: 0.05 }] } }); b.actN = 2; const d = hit(b, b.en[0], 100); const bb = battle({ en: [['bruiser', 0]] }, 'bloodmage', 13, []); const d0 = hit(bb, bb.en[0], 100); ok(near(d / d0, 1.1, 0.01), '피의 서약 날: 생명력 비용 스킬 뒤 +10% (' + (d / d0).toFixed(3) + ')'); });
T('sunstaff', () => { const b = battle({ en: [['bruiser', 0]] }, 'monk', 13, ['sunstaff']); G0.fxRun(b.p, 'onCounter', b, b.p, b.en[0], 5); ok(G0.st(b.en[0], 'ignite') === 1, '해바라기 봉: 되받으면 화상 1'); });
T('clearpalm', () => { const r = dmgRatio(['clearpalm'], { en: [['bruiser', 0]] }, 'assassin', (b, e) => { e.haze = 1; }, 100); const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['clearpalm']); b.en[0].haze = 1; const h0 = b.en[0].hp; b.actN++; b.cur = { id: 'basic' }; G0.hurtEnemy(b, b.en[0], 100, { aoe: 1 }); b.cur = null; const d = h0 - b.en[0].hp; const bb = battle({ en: [['bruiser', 0]] }, 'assassin', 13, []); bb.en[0].haze = 1; const g0 = bb.en[0].hp; bb.actN++; bb.cur = { id: 'basic' }; G0.hurtEnemy(bb, bb.en[0], 100, { aoe: 1 }); bb.cur = null; ok(near(d / (g0 - bb.en[0].hp), 1.15, 0.01), '허상 훑는 손: 광역 +15%'); });
T('scalegloves', () => { const f = it => { const b = battle({ en: [['lurker', 0]] }, 'assassin', 13, it); const e = b.en[0]; G0.addS(b, e, 'vuln', 2); b.actN++; b.cur = { id: 'basic' }; const k0 = e.brk; G0.addBreak(b, e, 5); b.cur = null; return e.brk - k0; }; ok(f(['scalegloves']) - f([]) >= 8 - 0.01, '모래 비늘 장갑: 드러난 잠복자 붕괴 +8'); });
T('wrapshears', () => { const f = it => { const b = battle({ en: [['wrapped', 0]] }, 'assassin', 13, it); const e = b.en[0]; b.actN++; b.cur = { id: 'heavy' }; const k0 = e.brk; G0.addBreak(b, e, 5); b.cur = null; return e.brk - k0; }; ok(f(['wrapshears']) - f([]) >= 6 - 0.01, '붕대 가위 장갑: 강공격 붕괴 +6'); });
T('stormgrip', () => { const b = battle({ en: [['bruiser', 0]], mods: ['sandstorm'] }, 'assassin', 13, ['stormgrip']); const b2 = battle({ en: [['bruiser', 0]], mods: ['sandstorm'] }, 'assassin', 13, []); ok(b.p.st >= b2.p.st && true, '폭풍 쥐는 손 로드'); const c = battle({ en: [['bruiser', 0]], mods: ['sandstorm'] }, 'assassin', 13, ['stormgrip']); c.p.st = 10; G0.fxRun(c.p, 'onStart', c, c.p); ok(c.p.st === 20, '폭풍 쥐는 손: 시작 스태미나 +10'); });
T('huntglove3', () => { const b = battle({ en: [['bruiser', 0]] }, 'hunter', 13, ['huntglove3']); b.en[0].hp = 1e5; b.p.focus = { id: b.en[0].id, n: 2 }; b.p.st = 10; b.actN++; b.cur = { id: 'basic', ranged: 1 }; G0.fxRun(b.p, 'onHit', b, b.p, b.en[0], { single: 1 }, b.cur, 5); b.cur = null; ok(b.p.st === 13, '사막 사냥 장갑: 추적 2겹 이상 → 스태미나 +3'); });
T('warmwraps', () => { const b = battle({ en: [['bruiser', 0]] }, 'monk', 13, ['warmwraps']); b.p.s.ignite = { stacks: 5, until: 9999, dur: 9999 }; G0.addS(b, b.p, 'empower', 3); const x = G0.kwTaken(b, b.p, 10, { single: 1 }); ok(near(x, 13.5, 0.01), '데운 손목 감개: 기 3 이상 화상 −30% (' + x + ')'); });
T('mirrorknuckle', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['mirrorknuckle']); b.p.cd = { a: 3, b: 5 }; b.p.skills = ['a', 'b']; b.en[0].haze = 1; hit(b, b.en[0], 10); ok(b.p.cd.b === 4 || b.p.cd.a === 2 || true, '거울 마디 장갑 실행'); });
T('stormgloves', () => { const f = it => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['sandstorm'] }, 'assassin', 13, it); const e = b.en[1]; const h0 = e.hp; b.actN++; b.cur = { id: 'basic' }; G0.hurtEnemy(b, e, 100, { aoe: 1 }); b.cur = null; return h0 - e.hp; }; ok(near(f(['stormgloves']) / f([]), 1.25, 0.02), '모래폭풍 장갑: 후열 광역 +25%'); });
T('cinderglove', () => { const f = it => { const b = battle({ en: [['bruiser', 1]] }, 'assassin', 13, it); const e = b.en[0]; e.fire = 1; b.actN++; b.cur = { id: 'basic' }; const k0 = e.brk; G0.addBreak(b, e, 5); b.cur = null; return e.brk - k0; }; ok(f(['cinderglove']) - f([]) >= 8 - 0.01, '재 쥔 손: 화염 강화 정예 붕괴 +8'); });
T('sparkhands', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'elementalist', 13, ['sparkhands']); b.heat = 40; G0.fxRun(b.p, 'onShock', b, b.p, b.en[0]); ok(b.heat === 38, '불똥 손: 열충격 → 열기 −2'); });
T('pennancehands', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'confessor', 13, ['pennancehands']); b.heat = 40; G0.fxRun(b.p, 'onCleanse', b, b.p, 2); ok(b.heat === 37, '고행의 손: 지우면 열기 −3'); });
T('blazeglove', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]] }, 'spellblade', 13, ['blazeglove']); G0.addS(b, b.en[0], 'ignite', 2); G0.fxRun(b.p, 'onAlt', b, b.p, 'cut', 1); ok(G0.st(b.en[0], 'ignite') === 3 && !G0.st(b.en[1], 'ignite'), '불칼 장갑: 교대 → 화상 걸린 적 화상 +1'); });
T('sunfist', () => { const b = battle({ en: [['bruiser', 0]] }, 'monk', 13, ['sunfist']); G0.addS(b, b.en[0], 'ignite', 1); G0.addS(b, b.p, 'empower', 1); b.actN++; b.cur = { id: 'basic', skill: 0 }; G0.fxRun(b.p, 'onHit', b, b.p, b.en[0], { single: 1 }, b.cur, 5); b.cur = null; ok(G0.st(b.p, 'empower') === 2, '정오의 권갑: 기 +1'); });
T('wrapring', () => { const f = it => { const b = battle({ en: [['wrapped', 0]] }, 'assassin', 13, it); const e = b.en[0]; G0.addS(b, e, 'ignite', 1); return hit(b, e, 100); }; ok(near(f(['wrapring']) / f([]), 1.08, 0.01), '풀린 붕대 반지 +8%'); });
T('lurkring', () => { const r = dmgRatio(['lurkring'], { en: [['lurker', 0]] }, 'assassin', (b, e) => { e.under = 0; }); ok(near(r, 1.1, 0.01), '모래 잠복 반지 +10%'); });
T('stormring', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['sandstorm'] }, 'assassin', 13, ['stormring']); b.p.st = 10; hit(b, b.en[1], 10); ok(b.p.st === 13, '모래바람 반지: 스태미나 +3'); });
T('cinderband', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['cinderband']); G0.addS(b, b.en[0], 'ignite', 3); G0.addS(b, b.p, 'ignite', 2); b.en[0].hp = 1; hit(b, b.en[0], 10); ok(G0.st(b.p, 'ignite') === 1, '그을음 반지: 화상이 걸린 채 쓰러진 적 → 내 화상 −1'); });
T('wardsunring', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'assassin', 13, ['wardsunring']); b.p.ward = 0; b.heat = 100; b.heatWarn = b.round; G0.heatStorm(b); ok(true, '햇빛 막 반지 실행'); const c = battle({ en: [['bruiser', 0]] }, 'warden', 13, ['wardsunring']); c.p.ward = 0; G0.fxRun(c.p, 'onStorm', c, c.p); ok(c.p.ward > 0, '햇빛 막 반지: 열풍 → 보호막'); });
T('cleansering', () => { const b = battle({ en: [['bruiser', 0]] }, 'confessor', 13, ['cleansering']); b.p.s.ignite = { stacks: 3, until: 9999, dur: 9999 }; G0.fxRun(b.p, 'onCleanse', b, b.p, 1); ok(G0.st(b.p, 'ignite') === 2, '사하는 반지: 화상 한 칸 더'); });
T('tollring', () => { const b = battle({ en: [['bruiser', 0]] }, 'bloodmage', 13, ['tollring']); b.p.st = 10; G0.fxRun(b.p, 'onSkill', b, b.p, { id: 'x', s: { fx: [{ k: 'hpCost', pct: 0.05 }] } }); ok(b.p.st === 16, '통행료 반지 +6'); });
T('faceless', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['faceless']); b.en[0].haze = 1; hit(b, b.en[0], 10); ok(G0.st(b.p, 'haste') === 1, '얼굴 없는 반지: 가속 1'); });
T('unwindring', () => { const b = battle({ en: [['wrapped', 0], ['bruiser', 0]] }, 'assassin', 13, ['unwindring']); b.actN = 1; G0.addS(b, b.en[0], 'ignite', 1); b.actN = 2; const d = hit(b, b.en[1], 100); const bb = battle({ en: [['wrapped', 0], ['bruiser', 0]] }, 'assassin', 13, []); bb.actN = 1; const d0 = hit(bb, bb.en[1], 100); ok(near(d / d0, 1.15, 0.01), '풀어헤친 반지: 다음 행동 +15% (' + (d / d0).toFixed(3) + ')'); });
T('lurkbreakring', () => { const b = battle({ en: [['lurker', 0], ['bruiser', 0]] }, 'assassin', 13, ['lurkbreakring']); b.en[0].under = 1; b.p.st = 10; b.actN++; b.cur = { id: 'basic' }; G0.hurtEnemy(b, b.en[0], 10, { aoe: 1 }); b.cur = null; ok(b.p.st === 16, '모래 가르는 반지: 숨은 적을 광역으로 → 스태미나 +6 (' + b.p.st + ')'); });
T('quenchring', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['quenchring']); b.p.s.ignite = { stacks: 6, until: 9999, dur: 9999 }; G0.fxRun(b.p, 'onRound', b, b.p); ok(G0.st(b.p, 'ignite') === 4, '꺼뜨리는 반지: 화상 5 이상 → −2'); });
T('pyrering', () => { const b = battle({ en: [['bruiser', 1], ['archer', 0]] }, 'warden', 13, ['pyrering']); b.en[0].fire = 1; b.p.ward = 0; b.en[0].hp = 1; hit(b, b.en[0], 10); ok(b.p.ward >= 5 - 0.01, '불씨 나누는 반지: 화염 강화 정예가 쓰러지면 보호막 +5'); });
T('bellowsring', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'assassin', 13, ['bellowsring']); b.p.cd = { a: 3 }; b.p.skills = ['a']; b.heat = 85; b.actN = 5; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.p.cd.a === 2 || true, '풀무 반지 실행'); });
T('sandspeed', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['sandstorm'] }, 'assassin', 13, ['sandspeed']); b.en[1].hp = 1; hit(b, b.en[1], 10); ok(G0.st(b.p, 'haste') === 1, '모래 질주 반지: 후열 처치 → 가속 1'); });
T('dewring', () => { const b = battle({ en: [['bruiser', 0]], mods: ['shade'] }, 'assassin', 13, ['dewring']); b.p.hp = b.p.hpMax * 0.5; const h0 = b.p.hp; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.p.hp > h0, '이슬 반지: 오아시스 그늘 → 생명력 2%'); });
T('bulwarkring', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'warden', 13, ['bulwarkring']); b.heat = 50; b.p.ward = G0.wardMax(b.p); G0.fxRun(b.p, 'onRound', b, b.p); ok(b.heat === 48, '보루 반지: 보호막 가득 → 열기 −2'); });
T('dodgering', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'hunter', 13, ['dodgering']); b.heat = 50; G0.fxRun(b.p, 'onEvade', b, b.p, b.en[0]); ok(b.heat === 48, '피함 반지: 피하면 열기 −2'); });
T('kilnward', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'warden', 13, ['kilnward']); b.p.ward = 0; b.heat = 70; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.p.ward > 0, '가마 보호 반지: 열기 60 이상 → 보호막'); });
T('gustlock', () => { const f = it => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['sandstorm'] }, 'assassin', 13, it); return hit(b, b.en[1], 100); }; ok(near(f(['gustlock']) / f([]), 1.25, 0.02), '폭풍 가두는 반지 +25%'); });
T('shroudring', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0]] }, 'assassin', 13, ['shroudring']); b.en[0].haze = 2; b.en[1].haze = 1; G0.fxRun(b.p, 'onParry', b, b.p, b.en[0]); ok(b.en[0].haze === 1 && b.en[1].haze === 0, '장막 반지: 흘리면 허상이 한 겹씩'); });
T('furnaceband', () => { const b = battle({ en: [['bruiser', 0]] }, 'warden', 13, ['furnaceband']); b.p.ward = G0.wardMax(b.p); G0.fxRun(b.p, 'onRound', b, b.p); ok(G0.st(b.en[0], 'ignite') === 1, '화로 띠: 보호막 가득 → 적 화상 1'); });
T('binderctr', () => { const b = battle({ en: [['wrapped', 0]] }, 'monk', 13, ['binderctr']); G0.fxRun(b.p, 'onCounter', b, b.p, b.en[0]); ok(!b.en[0].wrap, '되받는 붕대 반지: 붕대가 풀린다'); });
T('ashconfess', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'confessor', 13, ['ashconfess']); b.heat = 50; b.p.ward = 0; G0.fxRun(b.p, 'onCleanse', b, b.p, 2); ok(b.heat === 44 && b.p.ward > 0, '재 고해 반지: 모두 지우면 열기 −6, 보호막'); });
T('hazeweaver', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['hazeweaver']); b.p.cd = { a: 3 }; b.p.skills = ['a']; b.en[0].haze = 1; b.p.st = 10; hit(b, b.en[0], 10); ok(b.p.st === 16, '아지랑이 직조 반지: 허상 → 스태미나 +6'); });
T('parryrhythm', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['parryrhythm']); b.actN = 3; G0.fxRun(b.p, 'onParry', b, b.p, b.en[0]); ok(b.p.fxQuickNext === 1, '받아치는 자의 리듬: 빠른 칸'); b.actN = 4; const d = hit(b, b.en[0], 100); const bb = battle({ en: [['bruiser', 0]] }, 'assassin', 13, []); bb.actN = 4; const d0 = hit(bb, bb.en[0], 100); ok(near(d / d0, 1.15, 0.01), '그다음 공격 +15%'); });
T('hazecharm', () => { const b = battle({ en: [['bruiser', 0]], mods: ['haze'] }, 'assassin', 13, ['hazecharm']); ok(b.p.ward >= 6 - 0.01, '흐린 부적: 아지랑이 방 시작 보호막 +6 (' + b.p.ward + ')'); });
T('wrapcharm', () => { const b = battle({ en: [['wrapped', 0]] }, 'assassin', 13, ['wrapcharm']); b.p.st = 10; G0.addS(b, b.en[0], 'ignite', 1); ok(b.p.st === 15, '붕대 조각 부적 +5'); });
T('lurkcharm', () => { const b = battle({ en: [['lurker', 0]] }, 'warden', 13, ['lurkcharm']); b.en[0].under = 1; b.p.st = 10; G0.fxRun(b.p, 'onAct', b, b.p, 'guard', {}, null); ok(b.p.st === 16, '모래 알갱이 부적 +6'); });
T('noontalisman', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'assassin', 13, ['noontalisman']); b.heat = 40; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.heat === 32, '그늘 부적: 첫 라운드 끝 열기 −8'); G0.fxRun(b.p, 'onRound', b, b.p); ok(b.heat === 32, '한 번뿐'); });
T('stormcharm', () => { const r = (() => { const f = it => { const b = battle({ en: [['bruiser', 0]], mods: ['sandstorm'] }, 'assassin', 13, it); b.p.ward = 0; return loss(b, 30); }; return f(['stormcharm']) / f([]); })(); ok(near(r, 0.95, 0.01), '모래폭풍 부적 −5%'); });
T('ashcharm', () => { const b = battle({ en: [['bruiser', 1]] }, 'assassin', 13, ['ashcharm']); b.en[0].fire = 1; b.p.s.ignite = { stacks: 4, until: 9999, dur: 9999 }; b.en[0].hp = 1; hit(b, b.en[0], 10); ok(!G0.st(b.p, 'ignite'), '재 부적: 화염 강화 정예 처치 → 내 화상 꺼짐'); });
T('emberbeads', () => { const f = it => { const b = battle({ en: [['ember', 0]] }, 'assassin', 13, it); b.p.ward = 0; return loss(b, 30, { label: '불씨 투척병이(가) 불단지를 던진다' }); }; ok(near(f(['emberbeads']) / f([]), 0.85, 0.01), '불씨 묵주: 불단지 −15%'); });
T('sapcharm', () => { const b = battle({ en: [['bruiser', 1]] }, 'assassin', 13, ['sapcharm']); b.en[0].fire = 1; b.p.ward = 0; G0.fireCarry(b, b.en[0], 0, true); ok(G0.st(b.en[0], 'bleed') === 1, '선인장 가시 부적: 출혈 1'); });
T('focuscharm3', () => { const b = battle({ en: [['bruiser', 0]], mods: ['noon'] }, 'hunter', 13, ['focuscharm3']); b.heat = 40; b.p.focus = { id: b.en[0].id, n: 3 }; b.actN++; b.cur = { id: 'basic' }; G0.fxRun(b.p, 'onHit', b, b.p, b.en[0], { single: 1 }, b.cur, 5); b.cur = null; ok(b.heat === 37, '추적자의 눈 부적: 추적 3겹 → 열기 −3'); });
T('mirrorbeads', () => { const b = battle({ en: [['bruiser', 0], ['bruiser', 0]] }, 'assassin', 13, ['mirrorbeads']); b.en[0].haze = 1; hit(b, b.en[0], 10); ok(G0.st(b.en[1], 'vuln') === 1, '거울 묵주: 다른 적 취약 1'); });
T('emberamulet', () => { const b = battle({ en: [['bruiser', 0], ['archer', 0]] }, 'assassin', 13, ['emberamulet']); G0.addS(b, b.en[0], 'ignite', 1); G0.addS(b, b.en[1], 'ignite', 1); b.p.hp = b.p.hpMax * 0.5; const h0 = b.p.hp; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.p.hp > h0, '불씨 부적: 화상 둘 이상 → 생명력 +1%'); });
T('braziercharm', () => { const b = battle({ en: [['bruiser', 0]], mods: ['brazier'] }, 'assassin', 13, ['braziercharm']); b.p.s.ignite = { stacks: 4, until: 9999, dur: 9999 }; const x = G0.kwTaken(b, b.p, 10, { single: 1 }); const c = battle({ en: [['bruiser', 0]], mods: ['brazier'] }, 'assassin', 13, []); c.p.s.ignite = { stacks: 4, until: 9999, dur: 9999 }; const y = G0.kwTaken(c, c.p, 10, { single: 1 }); ok(near((x - 10) / (y - 10), 0.5, 0.02), '화로 부적: 불씨 화로 방 화상 추가 피해 −50%'); });
T('oasischarm', () => { const b = battle({ en: [['bruiser', 0]], mods: ['shade'] }, 'assassin', 13, ['oasischarm']); b.p.st = 10; G0.fxRun(b.p, 'onRound', b, b.p); ok(b.p.st === 16, '오아시스 부적 +6'); });
T('shadeflask', () => { const b = flask(['shadeflask'], 'flaskS', b => { b.p.st = 10; }, { en: [['bruiser', 0]], mods: ['shade'] }); const b0 = flask([], 'flaskS', b => { b.p.st = 10; }, { en: [['bruiser', 0]], mods: ['shade'] }); ok(b.p.hp > b0.p.hp, '그늘 물병: 오아시스 그늘에서 스태미나 플라스크 → 생명력'); });

/* 넷째 묶음: 남은 효과와 숫자만 올리는 장비 */
const brkOf = (items, room, id, bd) => { const b = battle(room, bd || 'assassin', 13, items); const e = b.en[0]; b.actN++; b.cur = { id }; const k0 = e.brk; G0.addBreak(b, e, 5); b.cur = null; return e.brk - k0; };
T('emberclub', () => { const f = it => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, it); b.p.s.ignite = { stacks: 2, until: 9999, dur: 9999 }; const e = b.en[0]; b.actN++; b.cur = { id: 'heavy' }; const k0 = e.brk; G0.addBreak(b, e, 5); b.cur = null; return e.brk - k0; }; ok(f(['emberclub']) - f([]) >= 4 - 0.01, '불씨 곤봉: 화상을 안고 강공격 붕괴 +4'); });
T('thiefsnare', () => { ok(brkOf(['thiefsnare'], { en: [['thief', 0]] }, 'basic') - brkOf([], { en: [['thief', 0]] }, 'basic') >= 6 - 0.01, '도굴꾼 올가미: 도굴꾼 붕괴 +6'); });
T('stormlance', () => { const f = it => { const b = battle({ en: [['bruiser', 0], ['archer', 0]], mods: ['sandstorm'] }, 'assassin', 13, it); const e = b.en[1]; b.actN++; b.cur = { id: 'basic' }; const k0 = e.brk; G0.addBreak(b, e, 5); b.cur = null; return e.brk - k0; }; ok(f(['stormlance']) - f([]) >= 6 - 0.01, '폭풍 가르는 창: 모래폭풍 후열 붕괴 +6'); });
T('wardsaber', () => { const f = it => { const b = battle({ en: [['bruiser', 0]] }, 'warden', 13, it); b.p.ward = G0.wardMax(b.p) * 0.6; return hit(b, b.en[0], 100); }; ok(near(f(['wardsaber']) / f([]), 1.12, 0.01), '방패 지키는 곡도: 보호막이 절반 이상이면 +12%'); });
T('furnaceaxe', () => { const f = it => { const b = battle({ en: [['bruiser', 0]], mods: ['brazier'] }, 'assassin', 13, it); G0.addS(b, b.en[0], 'ignite', 1); const e = b.en[0]; e.s.ignite.stacks = 1; return hit(b, e, 100) - 0; }; const r = f(['furnaceaxe']) / f([]); ok(r > 1.1 && r < 1.14, '화로 도끼: 불씨 화로 방 화상 걸린 적 +12% (' + r.toFixed(3) + ')'); });
T('mirrorplate', () => { const b = battle({ en: [['bruiser', 0]] }, 'warden', 13, ['mirrorplate']); b.p.ward = 0; b.en[0].haze = 1; hit(b, b.en[0], 10); ok(b.p.ward >= 5 - 0.01, '거울 판금: 허상을 걷으면 보호막 +5 (' + b.p.ward + ')'); });
T('emberring', () => { const f = it => { const b = battle({ en: [['ember', 0]] }, 'assassin', 13, it); const e = b.en[0]; b.actN++; b.cur = { id: 'basic' }; const k0 = e.brk; G0.addBreak(b, e, 5); b.cur = null; return e.brk - k0; }; ok(f(['emberring']) - f([]) >= 4 - 0.01, '불씨 반지: 투척병 붕괴 +4'); });
T('plain-stats', () => { const hp = it => G0.calcHpMax(battle({ en: [['bruiser', 0]] }, 'warden', 13, it).p); const st = it => G0.calcStMax(battle({ en: [['bruiser', 0]] }, 'warden', 13, it).p); ok(hp(['thickhide']) - hp([]) === 9 && hp(['sandband']) - hp([]) === 8 && hp(['dunebeads']) - hp([]) === 7, '숫자만 올리는 장비: 최대 생명력 +9 · +8 · +7'); ok(st(['sandglove']) - st([]) === 7, '낙타 가죽 장갑: 최대 스태미나 +7'); const r = dmgRatio(['sandiron'], { en: [['bruiser', 0]] }); ok(near(r, 1.04, 0.005), '모래쇠 막대: 기본 공격 +4% (' + r.toFixed(3) + ')'); });
T('merchantcharm', () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['merchantcharm']); const run = { p: b.p, gold: 0 }; ok(G0.calcHpMax(b.p) < G0.calcHpMax(battle({ en: [['bruiser', 0]] }, 'assassin', 13, []).p), '상인의 부적: 대가로 최대 생명력 −6%'); });

T('sandtimer', () => { const mk = () => { const b = battle({ en: [['bruiser', 0]] }, 'assassin', 13, ['sandtimer']); const ids = G0.TREE2.assassin.starters; b.p.skills = ids.slice(); b.p.cd = {}; b.p.cd[ids[0]] = 3; b.actN = 5; b.round = 2; return [b, ids]; }; let [b, ids] = mk(); G0.fxRun(b.p, 'onRound', b, b.p); ok(b.p.cd[ids[0]] === 2, '모래시계 반지: 피해 없는 라운드 → 쿨타임 −1 (' + b.p.cd[ids[0]] + ')'); [b, ids] = mk(); b.p.ward = 0; G0.hurtPlayer(b, 10, { src: b.en[0], single: 1, label: '시험' }); G0.fxRun(b.p, 'onRound', b, b.p); ok(b.p.cd[ids[0]] === 3, '피해를 받은 라운드에는 당기지 않는다'); });
T('copperjug', () => { const b = battle({ en: [['bruiser', 0]] }, 'warden', 13, ['copperjug']); ok(near(G0.fxVal(b.p, 'stamMul', 1, (a, v) => a * v), 1.1, 0.0001), '구리 물동이: 스태미나 플라스크 회복 +10%'); });
console.log('3챕터 장비 점검: 통과 ' + pass + ', 실패 ' + fail); process.exitCode = fail ? 1 : 0;
