/* 0.6a.2 직업 균형용 특정 상황 50종 (10월 3일 만든 사람 요청: 1챕터 던전이 아니라 정해 둔 상황으로 스킬 균형을 잡는다)
   범주 10개 × 5. 직업·갈래마다 "어느 범주에 강하고 어느 범주에 약한가"를 정해 두고(TREE2[직업].profile), tools/sitqa.js가 실제 승률과 맞는지 잰다.
   상황 하나: id, cat(범주), n(이름), room(던전 방과 같은 꼴: en [[역할, 정예]], tough [칸], mods, ambush, strong·foe(강적), boss(보스 종류), pre(시작 상태)), p(내 시작: hp 비율, st 스태미나, s 상태)
   몬스터 레벨: Lv5 판(1챕터 끝)은 lv5, Lv10 판(2챕터 끝)은 lv10. 적지 않으면 3과 7이다. 보스는 시험용 기준점이라 공개 문서의 이름만 쓴다 */
const SIT = [
  // 1. 무리: 약한 적이 여럿. 한 대상에 몰아치는 직업이 느리다
  { id: 1, cat: '무리', n: '하수인 넷', room: { en: [['minion', 0], ['minion', 0], ['minion', 0], ['minion', 0]] } },
  { id: 2, cat: '무리', n: '하수인 여섯', room: { en: [['minion', 0], ['minion', 0], ['minion', 0], ['minion', 0], ['minion', 0], ['minion', 0]] } },
  { id: 3, cat: '무리', n: '돌격병과 하수인 셋', room: { en: [['bruiser', 0], ['minion', 0], ['minion', 0], ['minion', 0]] } },
  { id: 4, cat: '무리', n: '소환사와 하수인 넷', room: { en: [['minion', 0], ['minion', 0], ['minion', 0], ['minion', 0], ['summoner', 0]] } },
  { id: 5, cat: '무리', n: '돌격병 넷', room: { en: [['bruiser', 0], ['bruiser', 0], ['bruiser', 0], ['bruiser', 0]] } },
  // 2. 강타: 강타를 모으는 근접 적. 흘리기·붕괴로 끊는 직업이 강하다
  { id: 6, cat: '강타', n: '강인한 정예 돌격병 둘', room: { en: [['bruiser', 1], ['bruiser', 1]], tough: [0, 1] } },
  { id: 7, cat: '강타', n: '정예 돌격병 둘', room: { en: [['bruiser', 1], ['bruiser', 1]] } },
  { id: 8, cat: '강타', n: '정예 돌격병 셋', room: { en: [['bruiser', 1], ['bruiser', 1], ['bruiser', 1]] } },
  { id: 9, cat: '강타', n: '강인한 정예 돌격병과 돌격병', room: { en: [['bruiser', 1], ['bruiser', 0]], tough: [0] } },
  { id: 10, cat: '강타', n: '굶주린 순례자', room: { en: [['bruiser', 0], ['minion', 0]], strong: '굶주린 순례자', foe: 'pilgrim' } },
  // 3. 후열: 방패병·하수인이 막고 사수가 뒤에서 쏜다. 후열에 닿는 직업이 강하다 (사수는 정예로 두지 않는다: 정예면 '거구' 성격과 섞여 무엇을 재는지 흐려진다)
  { id: 11, cat: '후열', n: '방패병과 사수 셋', room: { en: [['shield', 0], ['archer', 0], ['archer', 0], ['archer', 0]] } },
  { id: 12, cat: '후열', n: '방패병 둘과 사수 둘', room: { en: [['shield', 0], ['shield', 0], ['archer', 0], ['archer', 0]] } },
  { id: 13, cat: '후열', n: '강인한 방패병과 사수 둘', room: { en: [['shield', 0], ['archer', 0], ['archer', 0]], tough: [0] } },
  { id: 14, cat: '후열', n: '하수인 둘 뒤의 사수 셋', room: { en: [['minion', 0], ['minion', 0], ['archer', 0], ['archer', 0], ['archer', 0]] } },
  { id: 15, cat: '후열', n: '방패병 뒤의 치유사와 사수', room: { en: [['shield', 0], ['healer', 0], ['archer', 0]] } },
  // 4. 지원: 치유사·소환사가 뒤에서 버틴다. 공격하지 않는 적이 많아 흘릴 것이 적다
  { id: 16, cat: '지원', n: '치유사와 돌격병', room: { en: [['bruiser', 0], ['healer', 0]] } },
  { id: 17, cat: '지원', n: '방패병과 치유사 둘', room: { en: [['shield', 0], ['healer', 0], ['healer', 0]] } },
  { id: 18, cat: '지원', n: '소환사 둘과 방패병', room: { en: [['shield', 0], ['summoner', 0], ['summoner', 0]] } },
  { id: 19, cat: '지원', n: '치유사, 소환사, 돌격병', room: { en: [['bruiser', 0], ['healer', 0], ['summoner', 0]] } },
  { id: 20, cat: '지원', n: '정예 방패병과 치유사', room: { en: [['shield', 1], ['healer', 0]] } },
  // 5. 폭발: 자폭병이 몇 라운드 안에 터진다. 빨리 끊거나 버티는 직업이 강하다
  { id: 21, cat: '영창', n: '정예 화형 사제 둘', room: { en: [['pyre', 1], ['pyre', 1]] } }, // 10월 5일: 폭발 범주(자폭병)를 영창 범주(화형 사제)로 바꿨다
  { id: 22, cat: '영창', n: '방패병 둘 뒤의 화형 사제', room: { en: [['shield', 0], ['shield', 0], ['pyre', 0]] } },
  { id: 23, cat: '영창', n: '정예 화형 사제, 돌격병, 하수인', room: { en: [['pyre', 1], ['bruiser', 0], ['minion', 0]] } },
  { id: 24, cat: '영창', n: '하수인 셋 뒤의 화형 사제 둘', room: { en: [['minion', 0], ['minion', 0], ['minion', 0], ['pyre', 0], ['pyre', 0]] } },
  { id: 25, cat: '영창', n: '매복한 정예 화형 사제와 돌격병 둘', room: { en: [['pyre', 1], ['bruiser', 0], ['bruiser', 0]], ambush: 1 } },
  // 6. 거구: 체력이 큰 단일 적. 중독·터뜨리기·마무리가 강하다
  { id: 26, cat: '거구', n: '강인한 정예 방패병', room: { en: [['shield', 1]], tough: [0] } },
  { id: 27, cat: '거구', n: '종지기와 큰 종', room: { en: [['shield', 0]], strong: '종지기', foe: 'bellringer' } },
  { id: 28, cat: '거구', n: '타락한 수도원장 (챕터 보스 레벨)', room: { boss: 'abbot' }, lv: { 5: 4, 10: 8 } },
  { id: 29, cat: '거구', n: '강인한 굶주린 순례자', room: { en: [['bruiser', 0]], strong: '굶주린 순례자', foe: 'pilgrim', tough: [0] } },
  { id: 30, cat: '거구', n: '강인한 정예 돌격병', room: { en: [['bruiser', 1]], tough: [0] } },
  // 7. 상처: 나쁜 상태로 시작한다 (모두에게 같은 짐. 범주 목표 없음)
  { id: 31, cat: '상처', n: '출혈 6을 안고 사수 둘', room: { en: [['archer', 0], ['archer', 0]] }, p: { s: { bleed: 6 } } },
  { id: 32, cat: '상처', n: '약화·취약을 안고 돌격병 둘', room: { en: [['bruiser', 0], ['bruiser', 0]], pre: { weak: 3, vuln: 3 } } },
  { id: 33, cat: '상처', n: '중독 8을 안고 하수인 둘', room: { en: [['minion', 0], ['minion', 0]], pre: { poison: 8 } } },
  { id: 34, cat: '상처', n: '생명력 40%로 돌격병과 사수', room: { en: [['bruiser', 0], ['archer', 0]] }, p: { hp: 0.4 } },
  { id: 35, cat: '상처', n: '탈진한 채로 정예 돌격병', room: { en: [['bruiser', 1]] }, p: { st: 0 } },
  // 8. 특성: 방 특성 (범주 목표 없음)
  { id: 36, cat: '특성', n: '좁은 회랑: 돌격병 셋과 사수', room: { en: [['bruiser', 0], ['bruiser', 0], ['bruiser', 0], ['archer', 0]], mods: ['narrow'] } },
  { id: 37, cat: '특성', n: '피 웅덩이: 사수 둘과 돌격병', room: { en: [['bruiser', 0], ['archer', 0], ['archer', 0]], mods: ['bloodpool'] } },
  { id: 38, cat: '특성', n: '종소리: 하수인 셋과 돌격병', room: { en: [['bruiser', 0], ['minion', 0], ['minion', 0], ['minion', 0]], mods: ['bell'] } },
  { id: 39, cat: '특성', n: '무너지는 천장: 방패병과 치유사', room: { en: [['shield', 0], ['healer', 0]], mods: ['ceiling'] } },
  { id: 40, cat: '특성', n: '어둠: 사수 둘과 방패병', room: { en: [['shield', 0], ['archer', 0], ['archer', 0]], mods: ['dark'] } },
  // 9. 장기전: 단단한 적 여럿. 오래 쌓이는 피해가 강하다
  { id: 41, cat: '장기전', n: '방패병 셋', room: { en: [['shield', 0], ['shield', 0], ['shield', 0]] } },
  { id: 42, cat: '장기전', n: '정예 셋', room: { en: [['bruiser', 1], ['shield', 1], ['archer', 1]] } },
  { id: 43, cat: '장기전', n: '소환사와 방패병 둘', room: { en: [['shield', 0], ['shield', 0], ['summoner', 0]] } },
  { id: 44, cat: '장기전', n: '강인한 방패병 둘과 치유사', room: { en: [['shield', 0], ['shield', 0], ['healer', 0]], tough: [0, 1] } },
  { id: 45, cat: '장기전', n: '정예 방패병 둘', room: { en: [['shield', 1], ['shield', 1]] } },
  // 10. 혼합: 실전 같은 구성 (범주 목표 없음)
  { id: 46, cat: '혼합', n: '돌격병, 방패병, 사수, 치유사', room: { en: [['bruiser', 0], ['shield', 0], ['archer', 0], ['healer', 0]] } },
  { id: 47, cat: '혼합', n: '정예 돌격병, 자폭병, 사수', room: { en: [['bruiser', 1], ['bomber', 0], ['archer', 0]] } },
  { id: 48, cat: '혼합', n: '순례자와 하수인 둘', room: { en: [['bruiser', 0], ['minion', 0], ['minion', 0]], strong: '굶주린 순례자', foe: 'pilgrim' } },
  { id: 49, cat: '혼합', n: '정예 방패병, 정예 사수, 소환사', room: { en: [['shield', 1], ['archer', 1], ['summoner', 0]] } },
  { id: 50, cat: '혼합', n: '돌격병 둘, 자폭병, 치유사', room: { en: [['bruiser', 0], ['bruiser', 0], ['bomber', 0], ['healer', 0]] } },
];
const SIT_CATS = ['무리', '강타', '후열', '지원', '영창', '거구', '상처', '특성', '장기전', '혼합'];
/* 2챕터 50상황 (10월 7일): 같은 10범주를 2챕터 적(해골 더미 · 조이기 · 뼈벽 · 땅속 · 부푼 시체, 1챕터 역할의 2챕터 모습)으로 다시 짰다.
   SIT_CH=2로 sitqa.js가 읽는다(내 레벨 7 · 10, 몬스터 레벨 7 · 9). 강적은 STRONG_FOES의 구성 그대로, 보스는 지하묘지의 군주(몬스터 Lv8) */
const SIT2 = [
  { id: 101, cat: '무리', n: '해골 병사 넷', room: { en: [['skeleton', 0], ['skeleton', 0], ['skeleton', 0], ['skeleton', 0]] } },
  { id: 102, cat: '무리', n: '부푼 시체 둘과 해골 둘', room: { en: [['bloat', 0], ['bloat', 0], ['skeleton', 0], ['skeleton', 0]] } },
  { id: 103, cat: '무리', n: '곡하는 사제와 해골 셋', room: { en: [['skeleton', 0], ['skeleton', 0], ['skeleton', 0], ['healer', 0]] } },
  { id: 104, cat: '무리', n: '소환사와 해골 셋', room: { en: [['skeleton', 0], ['skeleton', 0], ['skeleton', 0], ['summoner', 0]] } },
  { id: 105, cat: '무리', n: '무너진 납골벽: 해골 셋', room: { en: [['skeleton', 0], ['skeleton', 0], ['skeleton', 0]], mods: ['bonepile'] } },
  { id: 106, cat: '강타', n: '정예 돌격병 둘', room: { en: [['bruiser', 1], ['bruiser', 1]] } },
  { id: 107, cat: '강타', n: '신속한 정예 돌격병 둘', room: { en: [['bruiser', 1], ['bruiser', 1]], swift: [0, 1] } },
  { id: 108, cat: '강타', n: '뼈 수집가', room: { en: [['bruiser', 1], ['skeleton', 0], ['skeleton', 0]], strong: '뼈 수집가', foe: 'collector' } },
  { id: 109, cat: '강타', n: '굴 파는 묘지기', room: { en: [['burrower', 1], ['skeleton', 0], ['skeleton', 0]], strong: '굴 파는 묘지기', foe: 'sexton' } },
  { id: 110, cat: '강타', n: '강인한 정예 돌격병과 해골', room: { en: [['bruiser', 1], ['skeleton', 0]], tough: [0] } },
  { id: 111, cat: '후열', n: '뼈 쌓는 자 뒤의 사수 둘', room: { en: [['shield', 0], ['mason', 0], ['archer', 0], ['archer', 0]] } },
  { id: 112, cat: '후열', n: '해골 둘 뒤의 사수 둘', room: { en: [['skeleton', 0], ['skeleton', 0], ['archer', 0], ['archer', 0]] } },
  { id: 113, cat: '후열', n: '방패병 뒤의 무덤 주술사 둘', room: { en: [['shield', 0], ['hexer', 0], ['hexer', 0]] } },
  { id: 114, cat: '후열', n: '굴 파는 시체와 사수 둘', room: { en: [['burrower', 0], ['archer', 0], ['archer', 0]] } },
  { id: 115, cat: '후열', n: '뼈 쌓는 자, 무덤 주술사, 방패병', room: { en: [['shield', 0], ['mason', 0], ['hexer', 0]] } },
  { id: 116, cat: '지원', n: '곡하는 사제와 해골 둘', room: { en: [['skeleton', 0], ['skeleton', 0], ['healer', 0]] } },
  { id: 117, cat: '지원', n: '방패병과 사제 둘', room: { en: [['shield', 0], ['healer', 0], ['healer', 0]] } },
  { id: 118, cat: '지원', n: '소환사와 뼈 쌓는 자', room: { en: [['bruiser', 0], ['summoner', 0], ['mason', 0]] } },
  { id: 119, cat: '지원', n: '역병 우물지기', room: { en: [['healer', 1], ['shield', 0], ['skeleton', 0]], strong: '역병 우물지기', foe: 'well' } },
  { id: 120, cat: '지원', n: '뼈 쌓는 자 둘과 돌격병', room: { en: [['bruiser', 0], ['mason', 0], ['mason', 0]] } },
  { id: 121, cat: '영창', n: '정예 장송 사제 둘', room: { en: [['pyre', 1], ['pyre', 1]] } },
  { id: 122, cat: '영창', n: '방패병 둘 뒤의 장송 사제', room: { en: [['shield', 0], ['shield', 0], ['pyre', 0]] } },
  { id: 123, cat: '영창', n: '해골 둘 뒤의 장송 사제', room: { en: [['skeleton', 0], ['skeleton', 0], ['pyre', 0]] } },
  { id: 124, cat: '영창', n: '뼈벽 뒤의 장송 사제', room: { en: [['shield', 0], ['mason', 0], ['pyre', 0]] } },
  { id: 125, cat: '영창', n: '정예 장송 사제와 무덤 주술사', room: { en: [['bruiser', 0], ['pyre', 1], ['hexer', 0]] } },
  { id: 126, cat: '거구', n: '강인한 정예 방패병', room: { en: [['shield', 1]], tough: [0] } },
  { id: 127, cat: '거구', n: '저주받은 기사', room: { en: [['shield', 1], ['hexer', 0]], strong: '저주받은 기사', foe: 'knight' } },
  { id: 128, cat: '거구', n: '지하묘지의 군주 (챕터 보스 레벨)', room: { boss: 'cryptlord' }, lv: { 7: 8, 10: 8 } },
  { id: 129, cat: '거구', n: '메아리 망령', room: { en: [['bruiser', 1], ['hexer', 0]], strong: '메아리 망령', foe: 'echo' } },
  { id: 130, cat: '거구', n: '강인한 정예 돌격병', room: { en: [['bruiser', 1]], tough: [0] } },
  { id: 131, cat: '상처', n: '중독 8을 안고 무덤 주술사 둘', room: { en: [['hexer', 0], ['hexer', 0]], pre: { poison: 8 } } },
  { id: 132, cat: '상처', n: '약화 · 취약을 안고 주술사와 해골', room: { en: [['skeleton', 0], ['hexer', 0]], pre: { weak: 3, vuln: 3 } } },
  { id: 133, cat: '상처', n: '출혈 6을 안고 사수 둘', room: { en: [['archer', 0], ['archer', 0]] }, p: { s: { bleed: 6 } } },
  { id: 134, cat: '상처', n: '생명력 40%로 부푼 시체 둘', room: { en: [['bloat', 0], ['bloat', 0]] }, p: { hp: 0.4 } },
  { id: 135, cat: '상처', n: '탈진한 채로 정예 돌격병', room: { en: [['bruiser', 1]] }, p: { st: 0 } },
  { id: 136, cat: '특성', n: '무너진 납골벽: 돌격병과 사수', room: { en: [['bruiser', 0], ['archer', 0]], mods: ['bonepile'] } },
  { id: 137, cat: '특성', n: '썩은 공기: 부푼 시체와 사수', room: { en: [['bloat', 0], ['bloat', 0], ['archer', 0]], mods: ['rotair'] } },
  { id: 138, cat: '특성', n: '물에 잠긴 바닥: 굴 파는 시체 둘', room: { en: [['burrower', 0], ['burrower', 0], ['archer', 0]], mods: ['flooded'] } },
  { id: 139, cat: '특성', n: '무너지는 천장: 방패병과 사제', room: { en: [['shield', 0], ['healer', 0]], mods: ['ceiling'] } },
  { id: 140, cat: '특성', n: '어둠: 해골 둘과 사수', room: { en: [['skeleton', 0], ['skeleton', 0], ['archer', 0]], mods: ['dark'] } },
  { id: 141, cat: '장기전', n: '방패병 셋', room: { en: [['shield', 0], ['shield', 0], ['shield', 0]] } },
  { id: 142, cat: '장기전', n: '정예 셋', room: { en: [['bruiser', 1], ['shield', 1], ['hexer', 1]] } },
  { id: 143, cat: '장기전', n: '뼈 쌓는 자와 방패병 둘', room: { en: [['shield', 0], ['shield', 0], ['mason', 0]] } },
  { id: 144, cat: '장기전', n: '강인한 방패병 둘과 사제', room: { en: [['shield', 0], ['shield', 0], ['healer', 0]], tough: [0, 1] } },
  { id: 145, cat: '장기전', n: '정예 해골 둘과 소환사', room: { en: [['skeleton', 1], ['skeleton', 1], ['summoner', 0]] } },
  { id: 146, cat: '혼합', n: '뼈 순찰 (하층)', room: { en: [['skeleton', 1], ['skeleton', 0], ['archer', 0]] } },
  { id: 147, cat: '혼합', n: '저주 매듭 (하층)', room: { en: [['shield', 0], ['hexer', 1], ['hexer', 0]] } },
  { id: 148, cat: '혼합', n: '굴 무리 (하층)', room: { en: [['burrower', 1], ['burrower', 0], ['archer', 0]] } },
  { id: 149, cat: '혼합', n: '납골당 수비대', room: { en: [['skeleton', 1], ['mason', 0], ['hexer', 0]] } },
  { id: 150, cat: '혼합', n: '장송 영창 (하층)', room: { en: [['shield', 0], ['skeleton', 0], ['pyre', 1]] } },
];
/* 3챕터 50상황 (10월 7일, docs/챕터/3챕터.md 18.4절 3): 같은 10범주를 3챕터 적(잠복 · 붕대 · 불씨 · 허상 · 열기 · 화염 강화, 1챕터 역할의 3챕터 모습)으로 다시 짰다.
   SIT_CH=3으로 sitqa.js가 읽는다(내 레벨 12 · 15, 몬스터 레벨 11 · 13. 트리는 10줄까지라 두 레벨의 차이는 능력치뿐이다). 강적은 STRONG_FOES의 구성 그대로, 보스는 재의 여왕(몬스터 Lv12) */
const SIT3 = [
  { id: 201, cat: '무리', n: '재 인형 넷', room: { en: [['minion', 0], ['minion', 0], ['minion', 0], ['minion', 0]] } },
  { id: 202, cat: '무리', n: '모래 잠복자 둘과 약탈자 둘', room: { en: [['lurker', 0], ['lurker', 0], ['bruiser', 0], ['bruiser', 0]] } },
  { id: 203, cat: '무리', n: '불탄 해골 셋과 모래 부르는 자', room: { en: [['skeleton', 0], ['skeleton', 0], ['skeleton', 0], ['summoner', 0]] } },
  { id: 204, cat: '무리', n: '사막 약탈자 넷', room: { en: [['bruiser', 0], ['bruiser', 0], ['bruiser', 0], ['bruiser', 0]] } },
  { id: 205, cat: '무리', n: '약탈자 셋과 아지랑이 술사', room: { en: [['bruiser', 0], ['bruiser', 0], ['bruiser', 0], ['mirage', 0]] } },
  { id: 206, cat: '강타', n: '정예 붕대 망자 둘', room: { en: [['wrapped', 1], ['wrapped', 1]] } },
  { id: 207, cat: '강타', n: '화염 강화 정예 약탈자 둘', room: { en: [['bruiser', 1], ['bruiser', 1]], fire: [0, 1] } },
  { id: 208, cat: '강타', n: '녹은 유리 거상', room: { en: [['bruiser', 1]], strong: '녹은 유리 거상', foe: 'colossus' } },
  { id: 209, cat: '강타', n: '모래 속 사냥꾼', room: { en: [['lurker', 1], ['archer', 0], ['bruiser', 0]], strong: '모래 속 사냥꾼', foe: 'stalker' } },
  { id: 210, cat: '강타', n: '정예 약탈자와 불씨 투척병', room: { en: [['bruiser', 1], ['ember', 0]] } },
  { id: 211, cat: '후열', n: '근위병 뒤의 투척병 둘', room: { en: [['shield', 0], ['ember', 0], ['ember', 0]] } },
  { id: 212, cat: '후열', n: '약탈자 둘 뒤의 궁수 둘', room: { en: [['bruiser', 0], ['bruiser', 0], ['archer', 0], ['archer', 0]] } },
  { id: 213, cat: '후열', n: '근위병 뒤의 아지랑이 술사 둘', room: { en: [['shield', 0], ['mirage', 0], ['mirage', 0]] } },
  { id: 214, cat: '후열', n: '모래 잠복자와 궁수 둘', room: { en: [['lurker', 0], ['archer', 0], ['archer', 0]] } },
  { id: 215, cat: '후열', n: '근위병, 검은 해의 주술사, 투척병', room: { en: [['shield', 0], ['darkmage', 0], ['ember', 0]] } },
  { id: 216, cat: '지원', n: '재의 무녀와 망자 둘', room: { en: [['wrapped', 0], ['wrapped', 0], ['healer', 0]] } },
  { id: 217, cat: '지원', n: '근위병과 무녀 둘', room: { en: [['shield', 0], ['healer', 0], ['healer', 0]] } },
  { id: 218, cat: '지원', n: '해시계 사제', room: { en: [['healer', 1], ['shield', 0], ['bruiser', 0]], strong: '해시계 사제', foe: 'sundial' } },
  { id: 219, cat: '지원', n: '아지랑이 술사와 약탈자 둘', room: { en: [['bruiser', 0], ['bruiser', 0], ['mirage', 0]] } },
  { id: 220, cat: '지원', n: '모래 부르는 자와 투척병', room: { en: [['bruiser', 0], ['summoner', 0], ['ember', 0]] } },
  { id: 221, cat: '영창', n: '정예 태양 영창자 둘', room: { en: [['pyre', 1], ['pyre', 1]] } },
  { id: 222, cat: '영창', n: '근위병 둘 뒤의 영창자', room: { en: [['shield', 0], ['shield', 0], ['pyre', 0]] } },
  { id: 223, cat: '영창', n: '망자 둘 뒤의 영창자', room: { en: [['wrapped', 0], ['wrapped', 0], ['pyre', 0]] } },
  { id: 224, cat: '영창', n: '아지랑이 술사와 영창자', room: { en: [['bruiser', 0], ['mirage', 0], ['pyre', 0]] } },
  { id: 225, cat: '영창', n: '정예 영창자와 투척병', room: { en: [['bruiser', 0], ['pyre', 1], ['ember', 0]] } },
  { id: 226, cat: '거구', n: '강인한 정예 망자', room: { en: [['wrapped', 1]], tough: [0] } },
  { id: 227, cat: '거구', n: '불씨 수확자', room: { en: [['bruiser', 1], ['ember', 0], ['bruiser', 0]], strong: '불씨 수확자', foe: 'reaper' } },
  { id: 228, cat: '거구', n: '재의 여왕 (챕터 보스 레벨)', room: { boss: 'queen' }, lv: { 12: 12, 15: 12 } },
  { id: 229, cat: '거구', n: '아지랑이 무희', room: { en: [['bruiser', 1], ['archer', 0]], strong: '아지랑이 무희', foe: 'dancer' } },
  { id: 230, cat: '거구', n: '강인한 정예 약탈자', room: { en: [['bruiser', 1]], tough: [0] } },
  { id: 231, cat: '상처', n: '화상 6을 안고 투척병 둘과 약탈자', room: { en: [['ember', 0], ['ember', 0], ['bruiser', 0]] }, p: { s: { ignite: 6 } } },
  { id: 232, cat: '상처', n: '출혈 6을 안고 잠복자 둘', room: { en: [['lurker', 0], ['lurker', 0]] }, p: { s: { bleed: 6 } } },
  { id: 233, cat: '상처', n: '약화 · 취약을 안고 망자와 주술사', room: { en: [['wrapped', 0], ['darkmage', 0]], pre: { weak: 3, vuln: 3 } } },
  { id: 234, cat: '상처', n: '생명력 40%로 약탈자 셋', room: { en: [['bruiser', 0], ['bruiser', 0], ['bruiser', 0]] }, p: { hp: 0.4 } },
  { id: 235, cat: '상처', n: '탈진한 채로 정예 망자', room: { en: [['wrapped', 1]] }, p: { st: 0 } },
  { id: 236, cat: '특성', n: '작열하는 한낮: 약탈자 둘과 투척병', room: { en: [['bruiser', 0], ['bruiser', 0], ['ember', 0]], mods: ['noon'] } },
  { id: 237, cat: '특성', n: '아지랑이: 약탈자 둘과 궁수', room: { en: [['bruiser', 0], ['bruiser', 0], ['archer', 0]], mods: ['haze'] } },
  { id: 238, cat: '특성', n: '모래폭풍: 근위병과 궁수 둘', room: { en: [['shield', 0], ['archer', 0], ['archer', 0]], mods: ['sandstorm'] } },
  { id: 239, cat: '특성', n: '불씨 화로: 약탈자와 투척병', room: { en: [['bruiser', 0], ['ember', 0]], mods: ['brazier'] } },
  { id: 240, cat: '특성', n: '오아시스 그늘: 근위병과 무녀', room: { en: [['shield', 0], ['healer', 0]], mods: ['shade'] } },
  { id: 241, cat: '장기전', n: '근위병 셋', room: { en: [['shield', 0], ['shield', 0], ['shield', 0]] } },
  { id: 242, cat: '장기전', n: '정예 셋', room: { en: [['bruiser', 1], ['shield', 1], ['wrapped', 1]] } },
  { id: 243, cat: '장기전', n: '붕대 망자 셋', room: { en: [['wrapped', 0], ['wrapped', 0], ['wrapped', 0]] } },
  { id: 244, cat: '장기전', n: '강인한 근위병 둘과 무녀', room: { en: [['shield', 0], ['shield', 0], ['healer', 0]], tough: [0, 1] } },
  { id: 245, cat: '장기전', n: '정예 불탄 해골 둘과 모래 부르는 자', room: { en: [['skeleton', 1], ['skeleton', 1], ['summoner', 0]] } },
  { id: 246, cat: '혼합', n: '모래 웅덩이 (하층)', room: { en: [['lurker', 1], ['lurker', 0], ['archer', 0]] } },
  { id: 247, cat: '혼합', n: '불 지르는 행렬 (하층)', room: { en: [['bruiser', 1], ['shield', 0], ['ember', 0]] } },
  { id: 248, cat: '혼합', n: '신기루 행렬', room: { en: [['bruiser', 1], ['bruiser', 0], ['mirage', 0]] } },
  { id: 249, cat: '혼합', n: '재 의식', room: { en: [['shield', 0], ['darkmage', 1], ['ember', 0]] } },
  { id: 250, cat: '혼합', n: '태양 영창', room: { en: [['shield', 1], ['pyre', 0], ['healer', 0]] } },
];
if (typeof module !== 'undefined') module.exports = { SIT, SIT2, SIT3, SIT_CATS };
